return {
	Accent = Color3.fromRGB(230, 50, 100),

	AcrylicMain = Color3.fromRGB(18, 10, 15),
	AcrylicBorder = Color3.fromRGB(155, 79, 107),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(92, 24, 44), Color3.fromRGB(11, 6, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(103, 49, 70),
	Tab = Color3.fromRGB(162, 92, 118),

	Element = Color3.fromRGB(150, 70, 100),
	ElementBorder = Color3.fromRGB(15, 8, 12),
	InElementBorder = Color3.fromRGB(155, 79, 107),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 70, 100),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 70, 100),

	DropdownFrame = Color3.fromRGB(171, 107, 131),
	DropdownHolder = Color3.fromRGB(17, 9, 14),
	DropdownBorder = Color3.fromRGB(14, 8, 12),
	DropdownOption = Color3.fromRGB(150, 70, 100),

	Keybind = Color3.fromRGB(150, 70, 100),

	Input = Color3.fromRGB(165, 97, 123),
	InputFocused = Color3.fromRGB(11, 6, 9),
	InputIndicator = Color3.fromRGB(176, 116, 138),

	Dialog = Color3.fromRGB(17, 9, 14),
	DialogHolder = Color3.fromRGB(15, 8, 12),
	DialogHolderLine = Color3.fromRGB(13, 7, 11),
	DialogButton = Color3.fromRGB(17, 9, 14),
	DialogButtonBorder = Color3.fromRGB(158, 84, 112),
	DialogBorder = Color3.fromRGB(150, 70, 100),
	DialogInput = Color3.fromRGB(36, 28, 33),
	DialogInputLine = Color3.fromRGB(176, 116, 138),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 70, 100),
	HoverChange = 0.06
}
