return {
	Accent = Color3.fromRGB(250, 170, 60),

	AcrylicMain = Color3.fromRGB(18, 14, 10),
	AcrylicBorder = Color3.fromRGB(155, 126, 88),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(99, 68, 27), Color3.fromRGB(11, 9, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(103, 82, 55),
	Tab = Color3.fromRGB(162, 136, 101),

	Element = Color3.fromRGB(150, 120, 80),
	ElementBorder = Color3.fromRGB(15, 11, 8),
	InElementBorder = Color3.fromRGB(155, 126, 88),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 120, 80),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 120, 80),

	DropdownFrame = Color3.fromRGB(171, 147, 115),
	DropdownHolder = Color3.fromRGB(17, 13, 9),
	DropdownBorder = Color3.fromRGB(14, 11, 8),
	DropdownOption = Color3.fromRGB(150, 120, 80),

	Keybind = Color3.fromRGB(150, 120, 80),

	Input = Color3.fromRGB(165, 140, 106),
	InputFocused = Color3.fromRGB(11, 9, 6),
	InputIndicator = Color3.fromRGB(176, 153, 123),

	Dialog = Color3.fromRGB(17, 13, 9),
	DialogHolder = Color3.fromRGB(15, 11, 8),
	DialogHolderLine = Color3.fromRGB(13, 10, 7),
	DialogButton = Color3.fromRGB(17, 13, 9),
	DialogButtonBorder = Color3.fromRGB(158, 130, 94),
	DialogBorder = Color3.fromRGB(150, 120, 80),
	DialogInput = Color3.fromRGB(36, 32, 28),
	DialogInputLine = Color3.fromRGB(176, 153, 123),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 120, 80),
	HoverChange = 0.06
}
