return {
	Accent = Color3.fromRGB(180, 180, 190),

	AcrylicMain = Color3.fromRGB(15, 15, 16),
	AcrylicBorder = Color3.fromRGB(107, 107, 112),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(72, 72, 76), Color3.fromRGB(9, 9, 10)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(70, 70, 73),
	Tab = Color3.fromRGB(118, 118, 123),

	Element = Color3.fromRGB(100, 100, 105),
	ElementBorder = Color3.fromRGB(12, 12, 13),
	InElementBorder = Color3.fromRGB(107, 107, 112),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(100, 100, 105),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(100, 100, 105),

	DropdownFrame = Color3.fromRGB(131, 131, 135),
	DropdownHolder = Color3.fromRGB(14, 14, 15),
	DropdownBorder = Color3.fromRGB(12, 12, 12),
	DropdownOption = Color3.fromRGB(100, 100, 105),

	Keybind = Color3.fromRGB(100, 100, 105),

	Input = Color3.fromRGB(123, 123, 127),
	InputFocused = Color3.fromRGB(9, 9, 10),
	InputIndicator = Color3.fromRGB(138, 138, 142),

	Dialog = Color3.fromRGB(14, 14, 15),
	DialogHolder = Color3.fromRGB(12, 12, 13),
	DialogHolderLine = Color3.fromRGB(11, 11, 12),
	DialogButton = Color3.fromRGB(14, 14, 15),
	DialogButtonBorder = Color3.fromRGB(112, 112, 117),
	DialogBorder = Color3.fromRGB(100, 100, 105),
	DialogInput = Color3.fromRGB(33, 33, 34),
	DialogInputLine = Color3.fromRGB(138, 138, 142),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(100, 100, 105),
	HoverChange = 0.06
}
