return {
	Accent = Color3.fromRGB(80, 230, 180),

	AcrylicMain = Color3.fromRGB(10, 15, 18),
	AcrylicBorder = Color3.fromRGB(88, 145, 136),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(34, 90, 74), Color3.fromRGB(6, 9, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(55, 96, 90),
	Tab = Color3.fromRGB(101, 153, 145),

	Element = Color3.fromRGB(80, 140, 130),
	ElementBorder = Color3.fromRGB(8, 12, 15),
	InElementBorder = Color3.fromRGB(88, 145, 136),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(80, 140, 130),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(80, 140, 130),

	DropdownFrame = Color3.fromRGB(115, 163, 155),
	DropdownHolder = Color3.fromRGB(9, 14, 17),
	DropdownBorder = Color3.fromRGB(8, 12, 14),
	DropdownOption = Color3.fromRGB(80, 140, 130),

	Keybind = Color3.fromRGB(80, 140, 130),

	Input = Color3.fromRGB(106, 157, 148),
	InputFocused = Color3.fromRGB(6, 9, 11),
	InputIndicator = Color3.fromRGB(123, 168, 161),

	Dialog = Color3.fromRGB(9, 14, 17),
	DialogHolder = Color3.fromRGB(8, 12, 15),
	DialogHolderLine = Color3.fromRGB(7, 11, 13),
	DialogButton = Color3.fromRGB(9, 14, 17),
	DialogButtonBorder = Color3.fromRGB(94, 149, 140),
	DialogBorder = Color3.fromRGB(80, 140, 130),
	DialogInput = Color3.fromRGB(28, 33, 36),
	DialogInputLine = Color3.fromRGB(123, 168, 161),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(80, 140, 130),
	HoverChange = 0.06
}
