return {
	Accent = Color3.fromRGB(150, 70, 180),

	AcrylicMain = Color3.fromRGB(14, 10, 18),
	AcrylicBorder = Color3.fromRGB(112, 84, 126),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(61, 31, 74), Color3.fromRGB(9, 6, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(73, 52, 84),
	Tab = Color3.fromRGB(123, 96, 136),

	Element = Color3.fromRGB(105, 75, 120),
	ElementBorder = Color3.fromRGB(11, 8, 15),
	InElementBorder = Color3.fromRGB(112, 84, 126),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(105, 75, 120),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(105, 75, 120),

	DropdownFrame = Color3.fromRGB(135, 111, 147),
	DropdownHolder = Color3.fromRGB(13, 9, 17),
	DropdownBorder = Color3.fromRGB(11, 8, 14),
	DropdownOption = Color3.fromRGB(105, 75, 120),

	Keybind = Color3.fromRGB(105, 75, 120),

	Input = Color3.fromRGB(127, 102, 140),
	InputFocused = Color3.fromRGB(9, 6, 11),
	InputIndicator = Color3.fromRGB(142, 120, 153),

	Dialog = Color3.fromRGB(13, 9, 17),
	DialogHolder = Color3.fromRGB(11, 8, 15),
	DialogHolderLine = Color3.fromRGB(10, 7, 13),
	DialogButton = Color3.fromRGB(13, 9, 17),
	DialogButtonBorder = Color3.fromRGB(117, 89, 130),
	DialogBorder = Color3.fromRGB(105, 75, 120),
	DialogInput = Color3.fromRGB(32, 28, 36),
	DialogInputLine = Color3.fromRGB(142, 120, 153),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(105, 75, 120),
	HoverChange = 0.06
}
