return {
	Accent = Color3.fromRGB(200, 40, 60),

	AcrylicMain = Color3.fromRGB(18, 10, 12),
	AcrylicBorder = Color3.fromRGB(145, 79, 88),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(81, 20, 28), Color3.fromRGB(11, 6, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(97, 49, 56),
	Tab = Color3.fromRGB(153, 92, 101),

	Element = Color3.fromRGB(140, 70, 80),
	ElementBorder = Color3.fromRGB(15, 8, 10),
	InElementBorder = Color3.fromRGB(145, 79, 88),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(140, 70, 80),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(140, 70, 80),

	DropdownFrame = Color3.fromRGB(163, 107, 115),
	DropdownHolder = Color3.fromRGB(17, 9, 11),
	DropdownBorder = Color3.fromRGB(14, 8, 9),
	DropdownOption = Color3.fromRGB(140, 70, 80),

	Keybind = Color3.fromRGB(140, 70, 80),

	Input = Color3.fromRGB(157, 97, 106),
	InputFocused = Color3.fromRGB(11, 6, 7),
	InputIndicator = Color3.fromRGB(168, 116, 123),

	Dialog = Color3.fromRGB(17, 9, 11),
	DialogHolder = Color3.fromRGB(15, 8, 10),
	DialogHolderLine = Color3.fromRGB(13, 7, 9),
	DialogButton = Color3.fromRGB(17, 9, 11),
	DialogButtonBorder = Color3.fromRGB(149, 84, 94),
	DialogBorder = Color3.fromRGB(140, 70, 80),
	DialogInput = Color3.fromRGB(36, 28, 30),
	DialogInputLine = Color3.fromRGB(168, 116, 123),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(140, 70, 80),
	HoverChange = 0.06
}
