return {
	Accent = Color3.fromRGB(220, 90, 120),

	AcrylicMain = Color3.fromRGB(250, 240, 242),
	AcrylicBorder = Color3.fromRGB(216, 194, 199),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(245, 217, 223), Color3.fromRGB(250, 241, 243)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(212, 204, 205),
	Tab = Color3.fromRGB(216, 194, 199),

	Element = Color3.fromRGB(228, 205, 210),
	ElementBorder = Color3.fromRGB(187, 180, 181),
	InElementBorder = Color3.fromRGB(205, 184, 189),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(228, 205, 210),
	ToggleToggled = Color3.fromRGB(220, 90, 120),

	SliderRail = Color3.fromRGB(228, 205, 210),

	DropdownFrame = Color3.fromRGB(193, 174, 178),
	DropdownHolder = Color3.fromRGB(250, 240, 242),
	DropdownBorder = Color3.fromRGB(200, 192, 193),
	DropdownOption = Color3.fromRGB(228, 205, 210),

	Keybind = Color3.fromRGB(228, 205, 210),

	Input = Color3.fromRGB(205, 184, 189),
	InputFocused = Color3.fromRGB(250, 242, 243),
	InputIndicator = Color3.fromRGB(159, 143, 147),

	Dialog = Color3.fromRGB(250, 240, 242),
	DialogHolder = Color3.fromRGB(237, 228, 229),
	DialogHolderLine = Color3.fromRGB(220, 211, 212),
	DialogButton = Color3.fromRGB(250, 240, 242),
	DialogButtonBorder = Color3.fromRGB(209, 188, 193),
	DialogBorder = Color3.fromRGB(228, 205, 210),
	DialogInput = Color3.fromRGB(237, 228, 229),
	DialogInputLine = Color3.fromRGB(171, 153, 157),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(228, 205, 210),
	HoverChange = 0.06
}
