return {
	Accent = Color3.fromRGB(200, 150, 90),

	AcrylicMain = Color3.fromRGB(16, 14, 11),
	AcrylicBorder = Color3.fromRGB(136, 117, 93),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(80, 61, 38), Color3.fromRGB(10, 9, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(90, 76, 59),
	Tab = Color3.fromRGB(145, 127, 105),

	Element = Color3.fromRGB(130, 110, 85),
	ElementBorder = Color3.fromRGB(13, 11, 9),
	InElementBorder = Color3.fromRGB(136, 117, 93),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(130, 110, 85),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(130, 110, 85),

	DropdownFrame = Color3.fromRGB(155, 139, 119),
	DropdownHolder = Color3.fromRGB(15, 13, 10),
	DropdownBorder = Color3.fromRGB(12, 11, 8),
	DropdownOption = Color3.fromRGB(130, 110, 85),

	Keybind = Color3.fromRGB(130, 110, 85),

	Input = Color3.fromRGB(148, 131, 110),
	InputFocused = Color3.fromRGB(10, 9, 7),
	InputIndicator = Color3.fromRGB(161, 146, 127),

	Dialog = Color3.fromRGB(15, 13, 10),
	DialogHolder = Color3.fromRGB(13, 11, 9),
	DialogHolderLine = Color3.fromRGB(12, 10, 8),
	DialogButton = Color3.fromRGB(15, 13, 10),
	DialogButtonBorder = Color3.fromRGB(140, 121, 98),
	DialogBorder = Color3.fromRGB(130, 110, 85),
	DialogInput = Color3.fromRGB(34, 32, 29),
	DialogInputLine = Color3.fromRGB(161, 146, 127),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(130, 110, 85),
	HoverChange = 0.06
}
