return {
	Accent = Color3.fromRGB(255, 110, 200),

	AcrylicMain = Color3.fromRGB(18, 12, 16),
	AcrylicBorder = Color3.fromRGB(155, 98, 145),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(100, 46, 80), Color3.fromRGB(11, 7, 10)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(103, 62, 96),
	Tab = Color3.fromRGB(162, 109, 153),

	Element = Color3.fromRGB(150, 90, 140),
	ElementBorder = Color3.fromRGB(15, 10, 13),
	InElementBorder = Color3.fromRGB(155, 98, 145),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 90, 140),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 90, 140),

	DropdownFrame = Color3.fromRGB(171, 123, 163),
	DropdownHolder = Color3.fromRGB(17, 11, 15),
	DropdownBorder = Color3.fromRGB(14, 9, 12),
	DropdownOption = Color3.fromRGB(150, 90, 140),

	Keybind = Color3.fromRGB(150, 90, 140),

	Input = Color3.fromRGB(165, 114, 157),
	InputFocused = Color3.fromRGB(11, 7, 10),
	InputIndicator = Color3.fromRGB(176, 131, 168),

	Dialog = Color3.fromRGB(17, 11, 15),
	DialogHolder = Color3.fromRGB(15, 10, 13),
	DialogHolderLine = Color3.fromRGB(13, 9, 12),
	DialogButton = Color3.fromRGB(17, 11, 15),
	DialogButtonBorder = Color3.fromRGB(158, 103, 149),
	DialogBorder = Color3.fromRGB(150, 90, 140),
	DialogInput = Color3.fromRGB(36, 30, 34),
	DialogInputLine = Color3.fromRGB(176, 131, 168),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 90, 140),
	HoverChange = 0.06
}
