return {
	Accent = Color3.fromRGB(180, 220, 70),

	AcrylicMain = Color3.fromRGB(14, 15, 12),
	AcrylicBorder = Color3.fromRGB(117, 136, 88),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(72, 86, 32), Color3.fromRGB(9, 9, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(76, 89, 56),
	Tab = Color3.fromRGB(127, 145, 101),

	Element = Color3.fromRGB(110, 130, 80),
	ElementBorder = Color3.fromRGB(11, 12, 10),
	InElementBorder = Color3.fromRGB(117, 136, 88),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(110, 130, 80),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(110, 130, 80),

	DropdownFrame = Color3.fromRGB(139, 155, 115),
	DropdownHolder = Color3.fromRGB(13, 14, 11),
	DropdownBorder = Color3.fromRGB(11, 12, 9),
	DropdownOption = Color3.fromRGB(110, 130, 80),

	Keybind = Color3.fromRGB(110, 130, 80),

	Input = Color3.fromRGB(131, 148, 106),
	InputFocused = Color3.fromRGB(9, 9, 7),
	InputIndicator = Color3.fromRGB(146, 161, 123),

	Dialog = Color3.fromRGB(13, 14, 11),
	DialogHolder = Color3.fromRGB(11, 12, 10),
	DialogHolderLine = Color3.fromRGB(10, 11, 9),
	DialogButton = Color3.fromRGB(13, 14, 11),
	DialogButtonBorder = Color3.fromRGB(121, 140, 94),
	DialogBorder = Color3.fromRGB(110, 130, 80),
	DialogInput = Color3.fromRGB(32, 33, 30),
	DialogInputLine = Color3.fromRGB(146, 161, 123),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(110, 130, 80),
	HoverChange = 0.06
}
