return {
	Accent = Color3.fromRGB(220, 60, 90),

	AcrylicMain = Color3.fromRGB(20, 12, 14),
	AcrylicBorder = Color3.fromRGB(145, 88, 98),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(90, 28, 40), Color3.fromRGB(13, 7, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(98, 56, 63),
	Tab = Color3.fromRGB(153, 101, 109),

	Element = Color3.fromRGB(140, 80, 90),
	ElementBorder = Color3.fromRGB(17, 10, 11),
	InElementBorder = Color3.fromRGB(145, 88, 98),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(140, 80, 90),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(140, 80, 90),

	DropdownFrame = Color3.fromRGB(163, 115, 123),
	DropdownHolder = Color3.fromRGB(19, 11, 13),
	DropdownBorder = Color3.fromRGB(16, 9, 11),
	DropdownOption = Color3.fromRGB(140, 80, 90),

	Keybind = Color3.fromRGB(140, 80, 90),

	Input = Color3.fromRGB(157, 106, 114),
	InputFocused = Color3.fromRGB(13, 7, 9),
	InputIndicator = Color3.fromRGB(168, 123, 131),

	Dialog = Color3.fromRGB(19, 11, 13),
	DialogHolder = Color3.fromRGB(17, 10, 11),
	DialogHolderLine = Color3.fromRGB(15, 9, 10),
	DialogButton = Color3.fromRGB(19, 11, 13),
	DialogButtonBorder = Color3.fromRGB(149, 94, 103),
	DialogBorder = Color3.fromRGB(140, 80, 90),
	DialogInput = Color3.fromRGB(37, 30, 32),
	DialogInputLine = Color3.fromRGB(168, 123, 131),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(140, 80, 90),
	HoverChange = 0.06
}
