return {
	Accent = Color3.fromRGB(70, 120, 230),

	AcrylicMain = Color3.fromRGB(12, 15, 25),
	AcrylicBorder = Color3.fromRGB(98, 117, 164),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(32, 51, 96), Color3.fromRGB(7, 9, 16)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(62, 76, 112),
	Tab = Color3.fromRGB(109, 127, 171),

	Element = Color3.fromRGB(90, 110, 160),
	ElementBorder = Color3.fromRGB(10, 12, 21),
	InElementBorder = Color3.fromRGB(98, 117, 164),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(90, 110, 160),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(90, 110, 160),

	DropdownFrame = Color3.fromRGB(123, 139, 179),
	DropdownHolder = Color3.fromRGB(11, 14, 23),
	DropdownBorder = Color3.fromRGB(9, 12, 20),
	DropdownOption = Color3.fromRGB(90, 110, 160),

	Keybind = Color3.fromRGB(90, 110, 160),

	Input = Color3.fromRGB(114, 131, 174),
	InputFocused = Color3.fromRGB(7, 9, 16),
	InputIndicator = Color3.fromRGB(131, 146, 183),

	Dialog = Color3.fromRGB(11, 14, 23),
	DialogHolder = Color3.fromRGB(10, 12, 21),
	DialogHolderLine = Color3.fromRGB(9, 11, 18),
	DialogButton = Color3.fromRGB(11, 14, 23),
	DialogButtonBorder = Color3.fromRGB(103, 121, 167),
	DialogBorder = Color3.fromRGB(90, 110, 160),
	DialogInput = Color3.fromRGB(30, 33, 41),
	DialogInputLine = Color3.fromRGB(131, 146, 183),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(90, 110, 160),
	HoverChange = 0.06
}
