return {
	Accent = Color3.fromRGB(180, 120, 80),

	AcrylicMain = Color3.fromRGB(16, 13, 11),
	AcrylicBorder = Color3.fromRGB(126, 103, 84),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(73, 50, 35), Color3.fromRGB(10, 8, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(83, 66, 52),
	Tab = Color3.fromRGB(136, 114, 96),

	Element = Color3.fromRGB(120, 95, 75),
	ElementBorder = Color3.fromRGB(13, 11, 9),
	InElementBorder = Color3.fromRGB(126, 103, 84),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(120, 95, 75),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(120, 95, 75),

	DropdownFrame = Color3.fromRGB(147, 127, 111),
	DropdownHolder = Color3.fromRGB(15, 12, 10),
	DropdownBorder = Color3.fromRGB(12, 10, 8),
	DropdownOption = Color3.fromRGB(120, 95, 75),

	Keybind = Color3.fromRGB(120, 95, 75),

	Input = Color3.fromRGB(140, 119, 102),
	InputFocused = Color3.fromRGB(10, 8, 7),
	InputIndicator = Color3.fromRGB(153, 135, 120),

	Dialog = Color3.fromRGB(15, 12, 10),
	DialogHolder = Color3.fromRGB(13, 11, 9),
	DialogHolderLine = Color3.fromRGB(12, 9, 8),
	DialogButton = Color3.fromRGB(15, 12, 10),
	DialogButtonBorder = Color3.fromRGB(130, 107, 89),
	DialogBorder = Color3.fromRGB(120, 95, 75),
	DialogInput = Color3.fromRGB(34, 31, 29),
	DialogInputLine = Color3.fromRGB(153, 135, 120),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(120, 95, 75),
	HoverChange = 0.06
}
