return {
	Accent = Color3.fromRGB(200, 110, 70),

	AcrylicMain = Color3.fromRGB(16, 13, 11),
	AcrylicBorder = Color3.fromRGB(136, 107, 88),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(80, 46, 31), Color3.fromRGB(10, 8, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(90, 69, 55),
	Tab = Color3.fromRGB(145, 118, 101),

	Element = Color3.fromRGB(130, 100, 80),
	ElementBorder = Color3.fromRGB(13, 11, 9),
	InElementBorder = Color3.fromRGB(136, 107, 88),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(130, 100, 80),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(130, 100, 80),

	DropdownFrame = Color3.fromRGB(155, 131, 115),
	DropdownHolder = Color3.fromRGB(15, 12, 10),
	DropdownBorder = Color3.fromRGB(12, 10, 8),
	DropdownOption = Color3.fromRGB(130, 100, 80),

	Keybind = Color3.fromRGB(130, 100, 80),

	Input = Color3.fromRGB(148, 123, 106),
	InputFocused = Color3.fromRGB(10, 8, 7),
	InputIndicator = Color3.fromRGB(161, 138, 123),

	Dialog = Color3.fromRGB(15, 12, 10),
	DialogHolder = Color3.fromRGB(13, 11, 9),
	DialogHolderLine = Color3.fromRGB(12, 9, 8),
	DialogButton = Color3.fromRGB(15, 12, 10),
	DialogButtonBorder = Color3.fromRGB(140, 112, 94),
	DialogBorder = Color3.fromRGB(130, 100, 80),
	DialogInput = Color3.fromRGB(34, 31, 29),
	DialogInputLine = Color3.fromRGB(161, 138, 123),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(130, 100, 80),
	HoverChange = 0.06
}
