return {
	Accent = Color3.fromRGB(220, 130, 80),

	AcrylicMain = Color3.fromRGB(18, 14, 12),
	AcrylicBorder = Color3.fromRGB(155, 117, 93),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(88, 54, 35), Color3.fromRGB(11, 9, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(103, 76, 59),
	Tab = Color3.fromRGB(162, 127, 105),

	Element = Color3.fromRGB(150, 110, 85),
	ElementBorder = Color3.fromRGB(15, 11, 10),
	InElementBorder = Color3.fromRGB(155, 117, 93),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 110, 85),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 110, 85),

	DropdownFrame = Color3.fromRGB(171, 139, 119),
	DropdownHolder = Color3.fromRGB(17, 13, 11),
	DropdownBorder = Color3.fromRGB(14, 11, 9),
	DropdownOption = Color3.fromRGB(150, 110, 85),

	Keybind = Color3.fromRGB(150, 110, 85),

	Input = Color3.fromRGB(165, 131, 110),
	InputFocused = Color3.fromRGB(11, 9, 7),
	InputIndicator = Color3.fromRGB(176, 146, 127),

	Dialog = Color3.fromRGB(17, 13, 11),
	DialogHolder = Color3.fromRGB(15, 11, 10),
	DialogHolderLine = Color3.fromRGB(13, 10, 9),
	DialogButton = Color3.fromRGB(17, 13, 11),
	DialogButtonBorder = Color3.fromRGB(158, 121, 98),
	DialogBorder = Color3.fromRGB(150, 110, 85),
	DialogInput = Color3.fromRGB(36, 32, 30),
	DialogInputLine = Color3.fromRGB(176, 146, 127),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 110, 85),
	HoverChange = 0.06
}
