return {
	Accent = Color3.fromRGB(230, 100, 170),

	AcrylicMain = Color3.fromRGB(250, 240, 246),
	AcrylicBorder = Color3.fromRGB(213, 194, 209),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(247, 219, 234), Color3.fromRGB(250, 241, 246)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(212, 204, 209),
	Tab = Color3.fromRGB(213, 194, 209),

	Element = Color3.fromRGB(225, 205, 220),
	ElementBorder = Color3.fromRGB(187, 180, 184),
	InElementBorder = Color3.fromRGB(202, 184, 198),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(225, 205, 220),
	ToggleToggled = Color3.fromRGB(230, 100, 170),

	SliderRail = Color3.fromRGB(225, 205, 220),

	DropdownFrame = Color3.fromRGB(191, 174, 187),
	DropdownHolder = Color3.fromRGB(250, 240, 246),
	DropdownBorder = Color3.fromRGB(200, 192, 196),
	DropdownOption = Color3.fromRGB(225, 205, 220),

	Keybind = Color3.fromRGB(225, 205, 220),

	Input = Color3.fromRGB(202, 184, 198),
	InputFocused = Color3.fromRGB(250, 242, 247),
	InputIndicator = Color3.fromRGB(157, 143, 154),

	Dialog = Color3.fromRGB(250, 240, 246),
	DialogHolder = Color3.fromRGB(237, 228, 233),
	DialogHolderLine = Color3.fromRGB(220, 211, 216),
	DialogButton = Color3.fromRGB(250, 240, 246),
	DialogButtonBorder = Color3.fromRGB(207, 188, 202),
	DialogBorder = Color3.fromRGB(225, 205, 220),
	DialogInput = Color3.fromRGB(237, 228, 233),
	DialogInputLine = Color3.fromRGB(168, 153, 165),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(225, 205, 220),
	HoverChange = 0.06
}
