return {
	Accent = Color3.fromRGB(230, 70, 70),

	AcrylicMain = Color3.fromRGB(20, 15, 15),
	AcrylicBorder = Color3.fromRGB(155, 98, 98),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(93, 34, 34), Color3.fromRGB(13, 9, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(104, 63, 63),
	Tab = Color3.fromRGB(162, 109, 109),

	Element = Color3.fromRGB(150, 90, 90),
	ElementBorder = Color3.fromRGB(17, 12, 12),
	InElementBorder = Color3.fromRGB(155, 98, 98),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 90, 90),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 90, 90),

	DropdownFrame = Color3.fromRGB(171, 123, 123),
	DropdownHolder = Color3.fromRGB(19, 14, 14),
	DropdownBorder = Color3.fromRGB(16, 12, 12),
	DropdownOption = Color3.fromRGB(150, 90, 90),

	Keybind = Color3.fromRGB(150, 90, 90),

	Input = Color3.fromRGB(165, 114, 114),
	InputFocused = Color3.fromRGB(13, 9, 9),
	InputIndicator = Color3.fromRGB(176, 131, 131),

	Dialog = Color3.fromRGB(19, 14, 14),
	DialogHolder = Color3.fromRGB(17, 12, 12),
	DialogHolderLine = Color3.fromRGB(15, 11, 11),
	DialogButton = Color3.fromRGB(19, 14, 14),
	DialogButtonBorder = Color3.fromRGB(158, 103, 103),
	DialogBorder = Color3.fromRGB(150, 90, 90),
	DialogInput = Color3.fromRGB(37, 33, 33),
	DialogInputLine = Color3.fromRGB(176, 131, 131),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 90, 90),
	HoverChange = 0.06
}
