return {
	Accent = Color3.fromRGB(255, 50, 180),

	AcrylicMain = Color3.fromRGB(12, 8, 18),
	AcrylicBorder = Color3.fromRGB(145, 79, 155),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(97, 22, 74), Color3.fromRGB(7, 5, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(95, 48, 103),
	Tab = Color3.fromRGB(153, 92, 162),

	Element = Color3.fromRGB(140, 70, 150),
	ElementBorder = Color3.fromRGB(10, 6, 15),
	InElementBorder = Color3.fromRGB(145, 79, 155),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(140, 70, 150),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(140, 70, 150),

	DropdownFrame = Color3.fromRGB(163, 107, 171),
	DropdownHolder = Color3.fromRGB(11, 7, 17),
	DropdownBorder = Color3.fromRGB(9, 6, 14),
	DropdownOption = Color3.fromRGB(140, 70, 150),

	Keybind = Color3.fromRGB(140, 70, 150),

	Input = Color3.fromRGB(157, 97, 165),
	InputFocused = Color3.fromRGB(7, 5, 11),
	InputIndicator = Color3.fromRGB(168, 116, 176),

	Dialog = Color3.fromRGB(11, 7, 17),
	DialogHolder = Color3.fromRGB(10, 6, 15),
	DialogHolderLine = Color3.fromRGB(9, 6, 13),
	DialogButton = Color3.fromRGB(11, 7, 17),
	DialogButtonBorder = Color3.fromRGB(149, 84, 158),
	DialogBorder = Color3.fromRGB(140, 70, 150),
	DialogInput = Color3.fromRGB(30, 26, 36),
	DialogInputLine = Color3.fromRGB(168, 116, 176),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(140, 70, 150),
	HoverChange = 0.06
}
