return {
    Accent = Color3.fromRGB(72, 138, 182),

    AcrylicMain = Color3.fromRGB(8, 8, 8),
    AcrylicBorder = Color3.fromRGB(150, 150, 150),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(10, 10, 10), Color3.fromRGB(4, 4, 4)),
    AcrylicNoise = 0.98,

    TitleBarLine = Color3.fromRGB(145, 145, 145),
    Tab = Color3.fromRGB(100, 100, 100),

    Element = Color3.fromRGB(25, 25, 25),
    ElementBorder = Color3.fromRGB(145, 145, 145),
    InElementBorder = Color3.fromRGB(135, 135, 135),
    ElementTransparency = 0.88,

    DropdownFrame = Color3.fromRGB(120, 120, 120),
    DropdownHolder = Color3.fromRGB(12, 12, 12),
    DropdownBorder = Color3.fromRGB(140, 140, 140),

    Dialog = Color3.fromRGB(14, 14, 14),
    DialogHolder = Color3.fromRGB(9, 9, 9),
    DialogHolderLine = Color3.fromRGB(140, 140, 140),
    DialogButton = Color3.fromRGB(15, 15, 15),
    DialogButtonBorder = Color3.fromRGB(145, 145, 145),
    DialogBorder = Color3.fromRGB(150, 150, 150),
    DialogInput = Color3.fromRGB(18, 18, 18),
    DialogInputLine = Color3.fromRGB(155, 155, 155)
}