return {
    Accent = Color3.fromRGB(72, 138, 182),

    AcrylicMain = Color3.fromRGB(8, 8, 8),
    AcrylicBorder = Color3.fromRGB(25, 25, 25),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(10, 10, 10), Color3.fromRGB(4, 4, 4)),
    AcrylicNoise = 0.98,

    TitleBarLine = Color3.fromRGB(28, 28, 28),
    Tab = Color3.fromRGB(35, 35, 35),

    Element = Color3.fromRGB(25, 25, 25),
    ElementBorder = Color3.fromRGB(10, 10, 10),
    InElementBorder = Color3.fromRGB(20, 20, 20),
    ElementTransparency = 0.88,

    DropdownFrame = Color3.fromRGB(35, 35, 35),
    DropdownHolder = Color3.fromRGB(12, 12, 12),
    DropdownBorder = Color3.fromRGB(8, 8, 8),

    Dialog = Color3.fromRGB(14, 14, 14),
    DialogHolder = Color3.fromRGB(9, 9, 9),
    DialogHolderLine = Color3.fromRGB(6, 6, 6),
    DialogButton = Color3.fromRGB(15, 15, 15),
    DialogButtonBorder = Color3.fromRGB(25, 25, 25),
    DialogBorder = Color3.fromRGB(22, 22, 22),
    DialogInput = Color3.fromRGB(18, 18, 18),
    DialogInputLine = Color3.fromRGB(45, 45, 45)
}