return {
    Accent = Color3.fromRGB(72, 138, 182),

    AcrylicMain = Color3.fromRGB(8, 8, 8),
    AcrylicBorder = Color3.fromRGB(255, 255, 255),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(10, 10, 10), Color3.fromRGB(4, 4, 4)),
    AcrylicNoise = 0.98,

    TitleBarLine = Color3.fromRGB(255, 255, 255),
    Tab = Color3.fromRGB(100, 100, 100),

    Element = Color3.fromRGB(25, 25, 25),
    ElementBorder = Color3.fromRGB(255, 255, 255),
    InElementBorder = Color3.fromRGB(255, 255, 255),
    ElementTransparency = 0.88,

    DropdownFrame = Color3.fromRGB(120, 120, 120),
    DropdownHolder = Color3.fromRGB(12, 12, 12),
    DropdownBorder = Color3.fromRGB(255, 255, 255),

    Dialog = Color3.fromRGB(14, 14, 14),
    DialogHolder = Color3.fromRGB(9, 9, 9),
    DialogHolderLine = Color3.fromRGB(255, 255, 255),
    DialogButton = Color3.fromRGB(15, 15, 15),
    DialogButtonBorder = Color3.fromRGB(255, 255, 255),
    DialogBorder = Color3.fromRGB(255, 255, 255),
    DialogInput = Color3.fromRGB(18, 18, 18),
    DialogInputLine = Color3.fromRGB(255, 255, 255)
}