return {
	Accent = Color3.fromRGB(60, 140, 220),

	AcrylicMain = Color3.fromRGB(8, 14, 22),
	AcrylicBorder = Color3.fromRGB(79, 107, 145),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(26, 58, 91), Color3.fromRGB(5, 9, 14)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(48, 69, 98),
	Tab = Color3.fromRGB(92, 118, 153),

	Element = Color3.fromRGB(70, 100, 140),
	ElementBorder = Color3.fromRGB(6, 11, 18),
	InElementBorder = Color3.fromRGB(79, 107, 145),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(70, 100, 140),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(70, 100, 140),

	DropdownFrame = Color3.fromRGB(107, 131, 163),
	DropdownHolder = Color3.fromRGB(7, 13, 20),
	DropdownBorder = Color3.fromRGB(6, 11, 17),
	DropdownOption = Color3.fromRGB(70, 100, 140),

	Keybind = Color3.fromRGB(70, 100, 140),

	Input = Color3.fromRGB(97, 123, 157),
	InputFocused = Color3.fromRGB(5, 9, 14),
	InputIndicator = Color3.fromRGB(116, 138, 168),

	Dialog = Color3.fromRGB(7, 13, 20),
	DialogHolder = Color3.fromRGB(6, 11, 18),
	DialogHolderLine = Color3.fromRGB(6, 10, 16),
	DialogButton = Color3.fromRGB(7, 13, 20),
	DialogButtonBorder = Color3.fromRGB(84, 112, 149),
	DialogBorder = Color3.fromRGB(70, 100, 140),
	DialogInput = Color3.fromRGB(26, 32, 38),
	DialogInputLine = Color3.fromRGB(116, 138, 168),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(70, 100, 140),
	HoverChange = 0.06
}
