return {
	Accent = Color3.fromRGB(90, 100, 220),

	AcrylicMain = Color3.fromRGB(8, 8, 16),
	AcrylicBorder = Color3.fromRGB(79, 84, 136),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(36, 40, 87), Color3.fromRGB(5, 5, 10)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(48, 51, 90),
	Tab = Color3.fromRGB(92, 96, 145),

	Element = Color3.fromRGB(70, 75, 130),
	ElementBorder = Color3.fromRGB(6, 6, 13),
	InElementBorder = Color3.fromRGB(79, 84, 136),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(70, 75, 130),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(70, 75, 130),

	DropdownFrame = Color3.fromRGB(107, 111, 155),
	DropdownHolder = Color3.fromRGB(7, 7, 15),
	DropdownBorder = Color3.fromRGB(6, 6, 12),
	DropdownOption = Color3.fromRGB(70, 75, 130),

	Keybind = Color3.fromRGB(70, 75, 130),

	Input = Color3.fromRGB(97, 102, 148),
	InputFocused = Color3.fromRGB(5, 5, 10),
	InputIndicator = Color3.fromRGB(116, 120, 161),

	Dialog = Color3.fromRGB(7, 7, 15),
	DialogHolder = Color3.fromRGB(6, 6, 13),
	DialogHolderLine = Color3.fromRGB(6, 6, 12),
	DialogButton = Color3.fromRGB(7, 7, 15),
	DialogButtonBorder = Color3.fromRGB(84, 89, 140),
	DialogBorder = Color3.fromRGB(70, 75, 130),
	DialogInput = Color3.fromRGB(26, 26, 34),
	DialogInputLine = Color3.fromRGB(116, 120, 161),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(70, 75, 130),
	HoverChange = 0.06
}
