return {
	Accent = Color3.fromRGB(200, 110, 160),

	AcrylicMain = Color3.fromRGB(16, 13, 18),
	AcrylicBorder = Color3.fromRGB(126, 103, 126),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(80, 46, 67), Color3.fromRGB(10, 8, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(83, 66, 84),
	Tab = Color3.fromRGB(136, 114, 136),

	Element = Color3.fromRGB(120, 95, 120),
	ElementBorder = Color3.fromRGB(13, 11, 15),
	InElementBorder = Color3.fromRGB(126, 103, 126),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(120, 95, 120),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(120, 95, 120),

	DropdownFrame = Color3.fromRGB(147, 127, 147),
	DropdownHolder = Color3.fromRGB(15, 12, 17),
	DropdownBorder = Color3.fromRGB(12, 10, 14),
	DropdownOption = Color3.fromRGB(120, 95, 120),

	Keybind = Color3.fromRGB(120, 95, 120),

	Input = Color3.fromRGB(140, 119, 140),
	InputFocused = Color3.fromRGB(10, 8, 11),
	InputIndicator = Color3.fromRGB(153, 135, 153),

	Dialog = Color3.fromRGB(15, 12, 17),
	DialogHolder = Color3.fromRGB(13, 11, 15),
	DialogHolderLine = Color3.fromRGB(12, 9, 13),
	DialogButton = Color3.fromRGB(15, 12, 17),
	DialogButtonBorder = Color3.fromRGB(130, 107, 130),
	DialogBorder = Color3.fromRGB(120, 95, 120),
	DialogInput = Color3.fromRGB(34, 31, 36),
	DialogInputLine = Color3.fromRGB(153, 135, 153),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(120, 95, 120),
	HoverChange = 0.06
}
