return {
	Accent = Color3.fromRGB(60, 200, 140),

	AcrylicMain = Color3.fromRGB(12, 20, 17),
	AcrylicBorder = Color3.fromRGB(98, 155, 126),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(28, 83, 60), Color3.fromRGB(7, 13, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(62, 104, 83),
	Tab = Color3.fromRGB(109, 162, 136),

	Element = Color3.fromRGB(90, 150, 120),
	ElementBorder = Color3.fromRGB(10, 17, 14),
	InElementBorder = Color3.fromRGB(98, 155, 126),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(90, 150, 120),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(90, 150, 120),

	DropdownFrame = Color3.fromRGB(123, 171, 147),
	DropdownHolder = Color3.fromRGB(11, 19, 16),
	DropdownBorder = Color3.fromRGB(9, 16, 13),
	DropdownOption = Color3.fromRGB(90, 150, 120),

	Keybind = Color3.fromRGB(90, 150, 120),

	Input = Color3.fromRGB(114, 165, 140),
	InputFocused = Color3.fromRGB(7, 13, 11),
	InputIndicator = Color3.fromRGB(131, 176, 153),

	Dialog = Color3.fromRGB(11, 19, 16),
	DialogHolder = Color3.fromRGB(10, 17, 14),
	DialogHolderLine = Color3.fromRGB(9, 15, 12),
	DialogButton = Color3.fromRGB(11, 19, 16),
	DialogButtonBorder = Color3.fromRGB(103, 158, 130),
	DialogBorder = Color3.fromRGB(90, 150, 120),
	DialogInput = Color3.fromRGB(30, 37, 35),
	DialogInputLine = Color3.fromRGB(131, 176, 153),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(90, 150, 120),
	HoverChange = 0.06
}
