return {
	Accent = Color3.fromRGB(90, 180, 90),

	AcrylicMain = Color3.fromRGB(12, 16, 12),
	AcrylicBorder = Color3.fromRGB(93, 126, 93),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(39, 73, 39), Color3.fromRGB(7, 10, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(59, 83, 59),
	Tab = Color3.fromRGB(105, 136, 105),

	Element = Color3.fromRGB(85, 120, 85),
	ElementBorder = Color3.fromRGB(10, 13, 10),
	InElementBorder = Color3.fromRGB(93, 126, 93),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(85, 120, 85),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(85, 120, 85),

	DropdownFrame = Color3.fromRGB(119, 147, 119),
	DropdownHolder = Color3.fromRGB(11, 15, 11),
	DropdownBorder = Color3.fromRGB(9, 12, 9),
	DropdownOption = Color3.fromRGB(85, 120, 85),

	Keybind = Color3.fromRGB(85, 120, 85),

	Input = Color3.fromRGB(110, 140, 110),
	InputFocused = Color3.fromRGB(7, 10, 7),
	InputIndicator = Color3.fromRGB(127, 153, 127),

	Dialog = Color3.fromRGB(11, 15, 11),
	DialogHolder = Color3.fromRGB(10, 13, 10),
	DialogHolderLine = Color3.fromRGB(9, 12, 9),
	DialogButton = Color3.fromRGB(11, 15, 11),
	DialogButtonBorder = Color3.fromRGB(98, 130, 98),
	DialogBorder = Color3.fromRGB(85, 120, 85),
	DialogInput = Color3.fromRGB(30, 34, 30),
	DialogInputLine = Color3.fromRGB(127, 153, 127),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(85, 120, 85),
	HoverChange = 0.06
}
