return {
	Accent = Color3.fromRGB(120, 200, 240),

	AcrylicMain = Color3.fromRGB(12, 18, 22),
	AcrylicBorder = Color3.fromRGB(107, 145, 164),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(49, 81, 98), Color3.fromRGB(7, 11, 14)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(69, 97, 111),
	Tab = Color3.fromRGB(118, 153, 171),

	Element = Color3.fromRGB(100, 140, 160),
	ElementBorder = Color3.fromRGB(10, 15, 18),
	InElementBorder = Color3.fromRGB(107, 145, 164),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(100, 140, 160),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(100, 140, 160),

	DropdownFrame = Color3.fromRGB(131, 163, 179),
	DropdownHolder = Color3.fromRGB(11, 17, 20),
	DropdownBorder = Color3.fromRGB(9, 14, 17),
	DropdownOption = Color3.fromRGB(100, 140, 160),

	Keybind = Color3.fromRGB(100, 140, 160),

	Input = Color3.fromRGB(123, 157, 174),
	InputFocused = Color3.fromRGB(7, 11, 14),
	InputIndicator = Color3.fromRGB(138, 168, 183),

	Dialog = Color3.fromRGB(11, 17, 20),
	DialogHolder = Color3.fromRGB(10, 15, 18),
	DialogHolderLine = Color3.fromRGB(9, 13, 16),
	DialogButton = Color3.fromRGB(11, 17, 20),
	DialogButtonBorder = Color3.fromRGB(112, 149, 167),
	DialogBorder = Color3.fromRGB(100, 140, 160),
	DialogInput = Color3.fromRGB(30, 36, 38),
	DialogInputLine = Color3.fromRGB(138, 168, 183),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(100, 140, 160),
	HoverChange = 0.06
}
