return {
	Accent = Color3.fromRGB(140, 140, 150),

	AcrylicMain = Color3.fromRGB(14, 14, 15),
	AcrylicBorder = Color3.fromRGB(98, 98, 103),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(58, 58, 62), Color3.fromRGB(9, 9, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(63, 63, 67),
	Tab = Color3.fromRGB(109, 109, 114),

	Element = Color3.fromRGB(90, 90, 95),
	ElementBorder = Color3.fromRGB(11, 11, 12),
	InElementBorder = Color3.fromRGB(98, 98, 103),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(90, 90, 95),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(90, 90, 95),

	DropdownFrame = Color3.fromRGB(123, 123, 127),
	DropdownHolder = Color3.fromRGB(13, 13, 14),
	DropdownBorder = Color3.fromRGB(11, 11, 12),
	DropdownOption = Color3.fromRGB(90, 90, 95),

	Keybind = Color3.fromRGB(90, 90, 95),

	Input = Color3.fromRGB(114, 114, 119),
	InputFocused = Color3.fromRGB(9, 9, 9),
	InputIndicator = Color3.fromRGB(131, 131, 135),

	Dialog = Color3.fromRGB(13, 13, 14),
	DialogHolder = Color3.fromRGB(11, 11, 12),
	DialogHolderLine = Color3.fromRGB(10, 10, 11),
	DialogButton = Color3.fromRGB(13, 13, 14),
	DialogButtonBorder = Color3.fromRGB(103, 103, 107),
	DialogBorder = Color3.fromRGB(90, 90, 95),
	DialogInput = Color3.fromRGB(32, 32, 33),
	DialogInputLine = Color3.fromRGB(131, 131, 135),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(90, 90, 95),
	HoverChange = 0.06
}
