return {
	Accent = Color3.fromRGB(80, 110, 230),

	AcrylicMain = Color3.fromRGB(8, 10, 18),
	AcrylicBorder = Color3.fromRGB(79, 93, 145),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(33, 45, 92), Color3.fromRGB(5, 6, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(48, 58, 97),
	Tab = Color3.fromRGB(92, 105, 153),

	Element = Color3.fromRGB(70, 85, 140),
	ElementBorder = Color3.fromRGB(6, 8, 15),
	InElementBorder = Color3.fromRGB(79, 93, 145),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(70, 85, 140),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(70, 85, 140),

	DropdownFrame = Color3.fromRGB(107, 119, 163),
	DropdownHolder = Color3.fromRGB(7, 9, 17),
	DropdownBorder = Color3.fromRGB(6, 8, 14),
	DropdownOption = Color3.fromRGB(70, 85, 140),

	Keybind = Color3.fromRGB(70, 85, 140),

	Input = Color3.fromRGB(97, 110, 157),
	InputFocused = Color3.fromRGB(5, 6, 11),
	InputIndicator = Color3.fromRGB(116, 127, 168),

	Dialog = Color3.fromRGB(7, 9, 17),
	DialogHolder = Color3.fromRGB(6, 8, 15),
	DialogHolderLine = Color3.fromRGB(6, 7, 13),
	DialogButton = Color3.fromRGB(7, 9, 17),
	DialogButtonBorder = Color3.fromRGB(84, 98, 149),
	DialogBorder = Color3.fromRGB(70, 85, 140),
	DialogInput = Color3.fromRGB(26, 28, 36),
	DialogInputLine = Color3.fromRGB(116, 127, 168),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(70, 85, 140),
	HoverChange = 0.06
}
