return {
	Accent = Color3.fromRGB(200, 90, 50),

	AcrylicMain = Color3.fromRGB(16, 13, 11),
	AcrylicBorder = Color3.fromRGB(136, 98, 79),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(80, 39, 24), Color3.fromRGB(10, 8, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(90, 63, 49),
	Tab = Color3.fromRGB(145, 109, 92),

	Element = Color3.fromRGB(130, 90, 70),
	ElementBorder = Color3.fromRGB(13, 11, 9),
	InElementBorder = Color3.fromRGB(136, 98, 79),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(130, 90, 70),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(130, 90, 70),

	DropdownFrame = Color3.fromRGB(155, 123, 107),
	DropdownHolder = Color3.fromRGB(15, 12, 10),
	DropdownBorder = Color3.fromRGB(12, 10, 8),
	DropdownOption = Color3.fromRGB(130, 90, 70),

	Keybind = Color3.fromRGB(130, 90, 70),

	Input = Color3.fromRGB(148, 114, 97),
	InputFocused = Color3.fromRGB(10, 8, 7),
	InputIndicator = Color3.fromRGB(161, 131, 116),

	Dialog = Color3.fromRGB(15, 12, 10),
	DialogHolder = Color3.fromRGB(13, 11, 9),
	DialogHolderLine = Color3.fromRGB(12, 9, 8),
	DialogButton = Color3.fromRGB(15, 12, 10),
	DialogButtonBorder = Color3.fromRGB(140, 103, 84),
	DialogBorder = Color3.fromRGB(130, 90, 70),
	DialogInput = Color3.fromRGB(34, 31, 29),
	DialogInputLine = Color3.fromRGB(161, 131, 116),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(130, 90, 70),
	HoverChange = 0.06
}
