return {
	Accent = Color3.fromRGB(200, 160, 60),

	AcrylicMain = Color3.fromRGB(250, 248, 238),
	AcrylicBorder = Color3.fromRGB(213, 207, 185),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(242, 234, 211), Color3.fromRGB(250, 248, 239)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(212, 210, 202),
	Tab = Color3.fromRGB(213, 207, 185),

	Element = Color3.fromRGB(225, 218, 195),
	ElementBorder = Color3.fromRGB(187, 186, 178),
	InElementBorder = Color3.fromRGB(202, 196, 175),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(225, 218, 195),
	ToggleToggled = Color3.fromRGB(200, 160, 60),

	SliderRail = Color3.fromRGB(225, 218, 195),

	DropdownFrame = Color3.fromRGB(191, 185, 165),
	DropdownHolder = Color3.fromRGB(250, 248, 238),
	DropdownBorder = Color3.fromRGB(200, 198, 190),
	DropdownOption = Color3.fromRGB(225, 218, 195),

	Keybind = Color3.fromRGB(225, 218, 195),

	Input = Color3.fromRGB(202, 196, 175),
	InputFocused = Color3.fromRGB(250, 249, 240),
	InputIndicator = Color3.fromRGB(157, 152, 136),

	Dialog = Color3.fromRGB(250, 248, 238),
	DialogHolder = Color3.fromRGB(237, 235, 226),
	DialogHolderLine = Color3.fromRGB(220, 218, 209),
	DialogButton = Color3.fromRGB(250, 248, 238),
	DialogButtonBorder = Color3.fromRGB(207, 200, 179),
	DialogBorder = Color3.fromRGB(225, 218, 195),
	DialogInput = Color3.fromRGB(237, 235, 226),
	DialogInputLine = Color3.fromRGB(168, 163, 146),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(225, 218, 195),
	HoverChange = 0.06
}
