return {
	Accent = Color3.fromRGB(70, 190, 130),

	AcrylicMain = Color3.fromRGB(10, 16, 14),
	AcrylicBorder = Color3.fromRGB(88, 136, 112),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(31, 76, 54), Color3.fromRGB(6, 10, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(55, 90, 73),
	Tab = Color3.fromRGB(101, 145, 123),

	Element = Color3.fromRGB(80, 130, 105),
	ElementBorder = Color3.fromRGB(8, 13, 11),
	InElementBorder = Color3.fromRGB(88, 136, 112),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(80, 130, 105),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(80, 130, 105),

	DropdownFrame = Color3.fromRGB(115, 155, 135),
	DropdownHolder = Color3.fromRGB(9, 15, 13),
	DropdownBorder = Color3.fromRGB(8, 12, 11),
	DropdownOption = Color3.fromRGB(80, 130, 105),

	Keybind = Color3.fromRGB(80, 130, 105),

	Input = Color3.fromRGB(106, 148, 127),
	InputFocused = Color3.fromRGB(6, 10, 9),
	InputIndicator = Color3.fromRGB(123, 161, 142),

	Dialog = Color3.fromRGB(9, 15, 13),
	DialogHolder = Color3.fromRGB(8, 13, 11),
	DialogHolderLine = Color3.fromRGB(7, 12, 10),
	DialogButton = Color3.fromRGB(9, 15, 13),
	DialogButtonBorder = Color3.fromRGB(94, 140, 117),
	DialogBorder = Color3.fromRGB(80, 130, 105),
	DialogInput = Color3.fromRGB(28, 34, 32),
	DialogInputLine = Color3.fromRGB(123, 161, 142),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(80, 130, 105),
	HoverChange = 0.06
}
