return {
	Accent = Color3.fromRGB(180, 150, 230),

	AcrylicMain = Color3.fromRGB(16, 14, 20),
	AcrylicBorder = Color3.fromRGB(126, 117, 155),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(73, 61, 93), Color3.fromRGB(10, 9, 13)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(83, 76, 104),
	Tab = Color3.fromRGB(136, 127, 162),

	Element = Color3.fromRGB(120, 110, 150),
	ElementBorder = Color3.fromRGB(13, 11, 17),
	InElementBorder = Color3.fromRGB(126, 117, 155),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(120, 110, 150),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(120, 110, 150),

	DropdownFrame = Color3.fromRGB(147, 139, 171),
	DropdownHolder = Color3.fromRGB(15, 13, 19),
	DropdownBorder = Color3.fromRGB(12, 11, 16),
	DropdownOption = Color3.fromRGB(120, 110, 150),

	Keybind = Color3.fromRGB(120, 110, 150),

	Input = Color3.fromRGB(140, 131, 165),
	InputFocused = Color3.fromRGB(10, 9, 13),
	InputIndicator = Color3.fromRGB(153, 146, 176),

	Dialog = Color3.fromRGB(15, 13, 19),
	DialogHolder = Color3.fromRGB(13, 11, 17),
	DialogHolderLine = Color3.fromRGB(12, 10, 15),
	DialogButton = Color3.fromRGB(15, 13, 19),
	DialogButtonBorder = Color3.fromRGB(130, 121, 158),
	DialogBorder = Color3.fromRGB(120, 110, 150),
	DialogInput = Color3.fromRGB(34, 32, 37),
	DialogInputLine = Color3.fromRGB(153, 146, 176),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(120, 110, 150),
	HoverChange = 0.06
}
