return {
	Accent = Color3.fromRGB(150, 110, 220),

	AcrylicMain = Color3.fromRGB(247, 244, 250),
	AcrylicBorder = Color3.fromRGB(207, 199, 218),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(232, 223, 245), Color3.fromRGB(247, 245, 250)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(209, 207, 212),
	Tab = Color3.fromRGB(207, 199, 218),

	Element = Color3.fromRGB(218, 210, 230),
	ElementBorder = Color3.fromRGB(185, 183, 187),
	InElementBorder = Color3.fromRGB(196, 189, 207),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(218, 210, 230),
	ToggleToggled = Color3.fromRGB(150, 110, 220),

	SliderRail = Color3.fromRGB(218, 210, 230),

	DropdownFrame = Color3.fromRGB(185, 178, 195),
	DropdownHolder = Color3.fromRGB(247, 244, 250),
	DropdownBorder = Color3.fromRGB(197, 195, 200),
	DropdownOption = Color3.fromRGB(218, 210, 230),

	Keybind = Color3.fromRGB(218, 210, 230),

	Input = Color3.fromRGB(196, 189, 207),
	InputFocused = Color3.fromRGB(248, 245, 250),
	InputIndicator = Color3.fromRGB(152, 147, 161),

	Dialog = Color3.fromRGB(247, 244, 250),
	DialogHolder = Color3.fromRGB(234, 231, 237),
	DialogHolderLine = Color3.fromRGB(217, 214, 220),
	DialogButton = Color3.fromRGB(247, 244, 250),
	DialogButtonBorder = Color3.fromRGB(200, 193, 211),
	DialogBorder = Color3.fromRGB(218, 210, 230),
	DialogInput = Color3.fromRGB(234, 231, 237),
	DialogInputLine = Color3.fromRGB(163, 157, 172),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(218, 210, 230),
	HoverChange = 0.06
}
