return {
	Accent = Color3.fromRGB(160, 130, 90),

	AcrylicMain = Color3.fromRGB(248, 244, 236),
	AcrylicBorder = Color3.fromRGB(209, 201, 188),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(234, 226, 214), Color3.fromRGB(248, 245, 237)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(210, 207, 200),
	Tab = Color3.fromRGB(209, 201, 188),

	Element = Color3.fromRGB(220, 212, 198),
	ElementBorder = Color3.fromRGB(186, 183, 177),
	InElementBorder = Color3.fromRGB(198, 190, 178),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(220, 212, 198),
	ToggleToggled = Color3.fromRGB(160, 130, 90),

	SliderRail = Color3.fromRGB(220, 212, 198),

	DropdownFrame = Color3.fromRGB(187, 180, 168),
	DropdownHolder = Color3.fromRGB(248, 244, 236),
	DropdownBorder = Color3.fromRGB(198, 195, 188),
	DropdownOption = Color3.fromRGB(220, 212, 198),

	Keybind = Color3.fromRGB(220, 212, 198),

	Input = Color3.fromRGB(198, 190, 178),
	InputFocused = Color3.fromRGB(249, 245, 238),
	InputIndicator = Color3.fromRGB(154, 148, 138),

	Dialog = Color3.fromRGB(248, 244, 236),
	DialogHolder = Color3.fromRGB(235, 231, 224),
	DialogHolderLine = Color3.fromRGB(218, 214, 207),
	DialogButton = Color3.fromRGB(248, 244, 236),
	DialogButtonBorder = Color3.fromRGB(202, 195, 182),
	DialogBorder = Color3.fromRGB(220, 212, 198),
	DialogInput = Color3.fromRGB(235, 231, 224),
	DialogInputLine = Color3.fromRGB(165, 159, 148),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(220, 212, 198),
	HoverChange = 0.06
}
