return {
	Accent = Color3.fromRGB(250, 90, 40),

	AcrylicMain = Color3.fromRGB(20, 12, 10),
	AcrylicBorder = Color3.fromRGB(155, 98, 79),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(100, 39, 20), Color3.fromRGB(13, 7, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(104, 62, 49),
	Tab = Color3.fromRGB(162, 109, 92),

	Element = Color3.fromRGB(150, 90, 70),
	ElementBorder = Color3.fromRGB(17, 10, 8),
	InElementBorder = Color3.fromRGB(155, 98, 79),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 90, 70),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 90, 70),

	DropdownFrame = Color3.fromRGB(171, 123, 107),
	DropdownHolder = Color3.fromRGB(19, 11, 9),
	DropdownBorder = Color3.fromRGB(16, 9, 8),
	DropdownOption = Color3.fromRGB(150, 90, 70),

	Keybind = Color3.fromRGB(150, 90, 70),

	Input = Color3.fromRGB(165, 114, 97),
	InputFocused = Color3.fromRGB(13, 7, 6),
	InputIndicator = Color3.fromRGB(176, 131, 116),

	Dialog = Color3.fromRGB(19, 11, 9),
	DialogHolder = Color3.fromRGB(17, 10, 8),
	DialogHolderLine = Color3.fromRGB(15, 9, 7),
	DialogButton = Color3.fromRGB(19, 11, 9),
	DialogButtonBorder = Color3.fromRGB(158, 103, 84),
	DialogBorder = Color3.fromRGB(150, 90, 70),
	DialogInput = Color3.fromRGB(37, 30, 28),
	DialogInputLine = Color3.fromRGB(176, 131, 116),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 90, 70),
	HoverChange = 0.06
}
