return {
	Accent = Color3.fromRGB(50, 200, 190),

	AcrylicMain = Color3.fromRGB(10, 20, 20),
	AcrylicBorder = Color3.fromRGB(88, 145, 141),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(24, 83, 79), Color3.fromRGB(6, 13, 13)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(55, 98, 94),
	Tab = Color3.fromRGB(101, 153, 149),

	Element = Color3.fromRGB(80, 140, 135),
	ElementBorder = Color3.fromRGB(8, 17, 17),
	InElementBorder = Color3.fromRGB(88, 145, 141),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(80, 140, 135),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(80, 140, 135),

	DropdownFrame = Color3.fromRGB(115, 163, 159),
	DropdownHolder = Color3.fromRGB(9, 19, 19),
	DropdownBorder = Color3.fromRGB(8, 16, 16),
	DropdownOption = Color3.fromRGB(80, 140, 135),

	Keybind = Color3.fromRGB(80, 140, 135),

	Input = Color3.fromRGB(106, 157, 153),
	InputFocused = Color3.fromRGB(6, 13, 13),
	InputIndicator = Color3.fromRGB(123, 168, 165),

	Dialog = Color3.fromRGB(9, 19, 19),
	DialogHolder = Color3.fromRGB(8, 17, 17),
	DialogHolderLine = Color3.fromRGB(7, 15, 15),
	DialogButton = Color3.fromRGB(9, 19, 19),
	DialogButtonBorder = Color3.fromRGB(94, 149, 144),
	DialogBorder = Color3.fromRGB(80, 140, 135),
	DialogInput = Color3.fromRGB(28, 37, 37),
	DialogInputLine = Color3.fromRGB(123, 168, 165),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(80, 140, 135),
	HoverChange = 0.06
}
