return {
	Accent = Color3.fromRGB(60, 190, 150),

	AcrylicMain = Color3.fromRGB(240, 250, 246),
	AcrylicBorder = Color3.fromRGB(190, 213, 204),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(213, 241, 231), Color3.fromRGB(241, 250, 246)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(204, 212, 209),
	Tab = Color3.fromRGB(190, 213, 204),

	Element = Color3.fromRGB(200, 225, 215),
	ElementBorder = Color3.fromRGB(180, 187, 184),
	InElementBorder = Color3.fromRGB(180, 202, 193),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(200, 225, 215),
	ToggleToggled = Color3.fromRGB(60, 190, 150),

	SliderRail = Color3.fromRGB(200, 225, 215),

	DropdownFrame = Color3.fromRGB(170, 191, 182),
	DropdownHolder = Color3.fromRGB(240, 250, 246),
	DropdownBorder = Color3.fromRGB(192, 200, 196),
	DropdownOption = Color3.fromRGB(200, 225, 215),

	Keybind = Color3.fromRGB(200, 225, 215),

	Input = Color3.fromRGB(180, 202, 193),
	InputFocused = Color3.fromRGB(242, 250, 247),
	InputIndicator = Color3.fromRGB(140, 157, 150),

	Dialog = Color3.fromRGB(240, 250, 246),
	DialogHolder = Color3.fromRGB(228, 237, 233),
	DialogHolderLine = Color3.fromRGB(211, 220, 216),
	DialogButton = Color3.fromRGB(240, 250, 246),
	DialogButtonBorder = Color3.fromRGB(184, 207, 197),
	DialogBorder = Color3.fromRGB(200, 225, 215),
	DialogInput = Color3.fromRGB(228, 237, 233),
	DialogInputLine = Color3.fromRGB(150, 168, 161),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(200, 225, 215),
	HoverChange = 0.06
}
