return {
	Accent = Color3.fromRGB(90, 220, 170),

	AcrylicMain = Color3.fromRGB(18, 14, 12),
	AcrylicBorder = Color3.fromRGB(107, 145, 126),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(43, 86, 67), Color3.fromRGB(11, 9, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(71, 95, 82),
	Tab = Color3.fromRGB(118, 153, 136),

	Element = Color3.fromRGB(100, 140, 120),
	ElementBorder = Color3.fromRGB(15, 11, 10),
	InElementBorder = Color3.fromRGB(107, 145, 126),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(100, 140, 120),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(100, 140, 120),

	DropdownFrame = Color3.fromRGB(131, 163, 147),
	DropdownHolder = Color3.fromRGB(17, 13, 11),
	DropdownBorder = Color3.fromRGB(14, 11, 9),
	DropdownOption = Color3.fromRGB(100, 140, 120),

	Keybind = Color3.fromRGB(100, 140, 120),

	Input = Color3.fromRGB(123, 157, 140),
	InputFocused = Color3.fromRGB(11, 9, 7),
	InputIndicator = Color3.fromRGB(138, 168, 153),

	Dialog = Color3.fromRGB(17, 13, 11),
	DialogHolder = Color3.fromRGB(15, 11, 10),
	DialogHolderLine = Color3.fromRGB(13, 10, 9),
	DialogButton = Color3.fromRGB(17, 13, 11),
	DialogButtonBorder = Color3.fromRGB(112, 149, 130),
	DialogBorder = Color3.fromRGB(100, 140, 120),
	DialogInput = Color3.fromRGB(36, 32, 30),
	DialogInputLine = Color3.fromRGB(138, 168, 153),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(100, 140, 120),
	HoverChange = 0.06
}
