return {
	Accent = Color3.fromRGB(170, 90, 230),

	AcrylicMain = Color3.fromRGB(16, 12, 25),
	AcrylicBorder = Color3.fromRGB(136, 107, 164),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(69, 39, 96), Color3.fromRGB(10, 7, 16)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(90, 69, 112),
	Tab = Color3.fromRGB(145, 118, 171),

	Element = Color3.fromRGB(130, 100, 160),
	ElementBorder = Color3.fromRGB(13, 10, 21),
	InElementBorder = Color3.fromRGB(136, 107, 164),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(130, 100, 160),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(130, 100, 160),

	DropdownFrame = Color3.fromRGB(155, 131, 179),
	DropdownHolder = Color3.fromRGB(15, 11, 23),
	DropdownBorder = Color3.fromRGB(12, 9, 20),
	DropdownOption = Color3.fromRGB(130, 100, 160),

	Keybind = Color3.fromRGB(130, 100, 160),

	Input = Color3.fromRGB(148, 123, 174),
	InputFocused = Color3.fromRGB(10, 7, 16),
	InputIndicator = Color3.fromRGB(161, 138, 183),

	Dialog = Color3.fromRGB(15, 11, 23),
	DialogHolder = Color3.fromRGB(13, 10, 21),
	DialogHolderLine = Color3.fromRGB(12, 9, 18),
	DialogButton = Color3.fromRGB(15, 11, 23),
	DialogButtonBorder = Color3.fromRGB(140, 112, 167),
	DialogBorder = Color3.fromRGB(130, 100, 160),
	DialogInput = Color3.fromRGB(34, 30, 41),
	DialogInputLine = Color3.fromRGB(161, 138, 183),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(130, 100, 160),
	HoverChange = 0.06
}
