return {
	Accent = Color3.fromRGB(60, 255, 220),

	AcrylicMain = Color3.fromRGB(10, 12, 14),
	AcrylicBorder = Color3.fromRGB(79, 145, 136),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(27, 97, 86), Color3.fromRGB(6, 7, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(49, 95, 89),
	Tab = Color3.fromRGB(92, 153, 145),

	Element = Color3.fromRGB(70, 140, 130),
	ElementBorder = Color3.fromRGB(8, 10, 11),
	InElementBorder = Color3.fromRGB(79, 145, 136),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(70, 140, 130),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(70, 140, 130),

	DropdownFrame = Color3.fromRGB(107, 163, 155),
	DropdownHolder = Color3.fromRGB(9, 11, 13),
	DropdownBorder = Color3.fromRGB(8, 9, 11),
	DropdownOption = Color3.fromRGB(70, 140, 130),

	Keybind = Color3.fromRGB(70, 140, 130),

	Input = Color3.fromRGB(97, 157, 148),
	InputFocused = Color3.fromRGB(6, 7, 9),
	InputIndicator = Color3.fromRGB(116, 168, 161),

	Dialog = Color3.fromRGB(9, 11, 13),
	DialogHolder = Color3.fromRGB(8, 10, 11),
	DialogHolderLine = Color3.fromRGB(7, 9, 10),
	DialogButton = Color3.fromRGB(9, 11, 13),
	DialogButtonBorder = Color3.fromRGB(84, 149, 140),
	DialogBorder = Color3.fromRGB(70, 140, 130),
	DialogInput = Color3.fromRGB(28, 30, 32),
	DialogInputLine = Color3.fromRGB(116, 168, 161),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(70, 140, 130),
	HoverChange = 0.06
}
