return {
	Accent = Color3.fromRGB(230, 180, 80),

	AcrylicMain = Color3.fromRGB(15, 13, 10),
	AcrylicBorder = Color3.fromRGB(155, 136, 98),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(90, 71, 34), Color3.fromRGB(9, 8, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(102, 89, 62),
	Tab = Color3.fromRGB(162, 145, 109),

	Element = Color3.fromRGB(150, 130, 90),
	ElementBorder = Color3.fromRGB(12, 11, 8),
	InElementBorder = Color3.fromRGB(155, 136, 98),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 130, 90),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 130, 90),

	DropdownFrame = Color3.fromRGB(171, 155, 123),
	DropdownHolder = Color3.fromRGB(14, 12, 9),
	DropdownBorder = Color3.fromRGB(12, 10, 8),
	DropdownOption = Color3.fromRGB(150, 130, 90),

	Keybind = Color3.fromRGB(150, 130, 90),

	Input = Color3.fromRGB(165, 148, 114),
	InputFocused = Color3.fromRGB(9, 8, 6),
	InputIndicator = Color3.fromRGB(176, 161, 131),

	Dialog = Color3.fromRGB(14, 12, 9),
	DialogHolder = Color3.fromRGB(12, 11, 8),
	DialogHolderLine = Color3.fromRGB(11, 9, 7),
	DialogButton = Color3.fromRGB(14, 12, 9),
	DialogButtonBorder = Color3.fromRGB(158, 140, 103),
	DialogBorder = Color3.fromRGB(150, 130, 90),
	DialogInput = Color3.fromRGB(33, 31, 28),
	DialogInputLine = Color3.fromRGB(176, 161, 131),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 130, 90),
	HoverChange = 0.06
}
