return {
	Accent = Color3.fromRGB(210, 60, 60),

	AcrylicMain = Color3.fromRGB(12, 10, 10),
	AcrylicBorder = Color3.fromRGB(126, 79, 79),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(81, 27, 27), Color3.fromRGB(7, 6, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(82, 49, 49),
	Tab = Color3.fromRGB(136, 92, 92),

	Element = Color3.fromRGB(120, 70, 70),
	ElementBorder = Color3.fromRGB(10, 8, 8),
	InElementBorder = Color3.fromRGB(126, 79, 79),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(120, 70, 70),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(120, 70, 70),

	DropdownFrame = Color3.fromRGB(147, 107, 107),
	DropdownHolder = Color3.fromRGB(11, 9, 9),
	DropdownBorder = Color3.fromRGB(9, 8, 8),
	DropdownOption = Color3.fromRGB(120, 70, 70),

	Keybind = Color3.fromRGB(120, 70, 70),

	Input = Color3.fromRGB(140, 97, 97),
	InputFocused = Color3.fromRGB(7, 6, 6),
	InputIndicator = Color3.fromRGB(153, 116, 116),

	Dialog = Color3.fromRGB(11, 9, 9),
	DialogHolder = Color3.fromRGB(10, 8, 8),
	DialogHolderLine = Color3.fromRGB(9, 7, 7),
	DialogButton = Color3.fromRGB(11, 9, 9),
	DialogButtonBorder = Color3.fromRGB(130, 84, 84),
	DialogBorder = Color3.fromRGB(120, 70, 70),
	DialogInput = Color3.fromRGB(30, 28, 28),
	DialogInputLine = Color3.fromRGB(153, 116, 116),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(120, 70, 70),
	HoverChange = 0.06
}
