return {
	Accent = Color3.fromRGB(240, 140, 90),

	AcrylicMain = Color3.fromRGB(250, 242, 235),
	AcrylicBorder = Color3.fromRGB(216, 199, 188),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(248, 226, 213), Color3.fromRGB(250, 243, 237)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(212, 205, 199),
	Tab = Color3.fromRGB(216, 199, 188),

	Element = Color3.fromRGB(228, 210, 198),
	ElementBorder = Color3.fromRGB(187, 181, 176),
	InElementBorder = Color3.fromRGB(205, 189, 178),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(228, 210, 198),
	ToggleToggled = Color3.fromRGB(240, 140, 90),

	SliderRail = Color3.fromRGB(228, 210, 198),

	DropdownFrame = Color3.fromRGB(193, 178, 168),
	DropdownHolder = Color3.fromRGB(250, 242, 235),
	DropdownBorder = Color3.fromRGB(200, 193, 188),
	DropdownOption = Color3.fromRGB(228, 210, 198),

	Keybind = Color3.fromRGB(228, 210, 198),

	Input = Color3.fromRGB(205, 189, 178),
	InputFocused = Color3.fromRGB(250, 243, 238),
	InputIndicator = Color3.fromRGB(159, 147, 138),

	Dialog = Color3.fromRGB(250, 242, 235),
	DialogHolder = Color3.fromRGB(237, 229, 223),
	DialogHolderLine = Color3.fromRGB(220, 212, 206),
	DialogButton = Color3.fromRGB(250, 242, 235),
	DialogButtonBorder = Color3.fromRGB(209, 193, 182),
	DialogBorder = Color3.fromRGB(228, 210, 198),
	DialogInput = Color3.fromRGB(237, 229, 223),
	DialogInputLine = Color3.fromRGB(171, 157, 148),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(228, 210, 198),
	HoverChange = 0.06
}
