return {
	Accent = Color3.fromRGB(180, 90, 170),

	AcrylicMain = Color3.fromRGB(18, 12, 20),
	AcrylicBorder = Color3.fromRGB(126, 98, 126),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(74, 39, 72), Color3.fromRGB(11, 7, 13)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(84, 62, 85),
	Tab = Color3.fromRGB(136, 109, 136),

	Element = Color3.fromRGB(120, 90, 120),
	ElementBorder = Color3.fromRGB(15, 10, 17),
	InElementBorder = Color3.fromRGB(126, 98, 126),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(120, 90, 120),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(120, 90, 120),

	DropdownFrame = Color3.fromRGB(147, 123, 147),
	DropdownHolder = Color3.fromRGB(17, 11, 19),
	DropdownBorder = Color3.fromRGB(14, 9, 16),
	DropdownOption = Color3.fromRGB(120, 90, 120),

	Keybind = Color3.fromRGB(120, 90, 120),

	Input = Color3.fromRGB(140, 114, 140),
	InputFocused = Color3.fromRGB(11, 7, 13),
	InputIndicator = Color3.fromRGB(153, 131, 153),

	Dialog = Color3.fromRGB(17, 11, 19),
	DialogHolder = Color3.fromRGB(15, 10, 17),
	DialogHolderLine = Color3.fromRGB(13, 9, 15),
	DialogButton = Color3.fromRGB(17, 11, 19),
	DialogButtonBorder = Color3.fromRGB(130, 103, 130),
	DialogBorder = Color3.fromRGB(120, 90, 120),
	DialogInput = Color3.fromRGB(36, 30, 37),
	DialogInputLine = Color3.fromRGB(153, 131, 153),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(120, 90, 120),
	HoverChange = 0.06
}
