return {
	Accent = Color3.fromRGB(90, 110, 220),

	AcrylicMain = Color3.fromRGB(248, 248, 250),
	AcrylicBorder = Color3.fromRGB(204, 206, 213),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(224, 227, 245), Color3.fromRGB(248, 248, 250)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(210, 210, 212),
	Tab = Color3.fromRGB(204, 206, 213),

	Element = Color3.fromRGB(215, 217, 225),
	ElementBorder = Color3.fromRGB(186, 186, 187),
	InElementBorder = Color3.fromRGB(193, 195, 202),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(215, 217, 225),
	ToggleToggled = Color3.fromRGB(90, 110, 220),

	SliderRail = Color3.fromRGB(215, 217, 225),

	DropdownFrame = Color3.fromRGB(182, 184, 191),
	DropdownHolder = Color3.fromRGB(248, 248, 250),
	DropdownBorder = Color3.fromRGB(198, 198, 200),
	DropdownOption = Color3.fromRGB(215, 217, 225),

	Keybind = Color3.fromRGB(215, 217, 225),

	Input = Color3.fromRGB(193, 195, 202),
	InputFocused = Color3.fromRGB(249, 249, 250),
	InputIndicator = Color3.fromRGB(150, 151, 157),

	Dialog = Color3.fromRGB(248, 248, 250),
	DialogHolder = Color3.fromRGB(235, 235, 237),
	DialogHolderLine = Color3.fromRGB(218, 218, 220),
	DialogButton = Color3.fromRGB(248, 248, 250),
	DialogButtonBorder = Color3.fromRGB(197, 199, 207),
	DialogBorder = Color3.fromRGB(215, 217, 225),
	DialogInput = Color3.fromRGB(235, 235, 237),
	DialogInputLine = Color3.fromRGB(161, 162, 168),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(215, 217, 225),
	HoverChange = 0.06
}
