return {
	Accent = Color3.fromRGB(210, 110, 130),

	AcrylicMain = Color3.fromRGB(20, 14, 16),
	AcrylicBorder = Color3.fromRGB(155, 107, 117),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(86, 47, 55), Color3.fromRGB(13, 9, 10)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(104, 69, 77),
	Tab = Color3.fromRGB(162, 118, 127),

	Element = Color3.fromRGB(150, 100, 110),
	ElementBorder = Color3.fromRGB(17, 11, 13),
	InElementBorder = Color3.fromRGB(155, 107, 117),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(150, 100, 110),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(150, 100, 110),

	DropdownFrame = Color3.fromRGB(171, 131, 139),
	DropdownHolder = Color3.fromRGB(19, 13, 15),
	DropdownBorder = Color3.fromRGB(16, 11, 12),
	DropdownOption = Color3.fromRGB(150, 100, 110),

	Keybind = Color3.fromRGB(150, 100, 110),

	Input = Color3.fromRGB(165, 123, 131),
	InputFocused = Color3.fromRGB(13, 9, 10),
	InputIndicator = Color3.fromRGB(176, 138, 146),

	Dialog = Color3.fromRGB(19, 13, 15),
	DialogHolder = Color3.fromRGB(17, 11, 13),
	DialogHolderLine = Color3.fromRGB(15, 10, 12),
	DialogButton = Color3.fromRGB(19, 13, 15),
	DialogButtonBorder = Color3.fromRGB(158, 112, 121),
	DialogBorder = Color3.fromRGB(150, 100, 110),
	DialogInput = Color3.fromRGB(37, 32, 34),
	DialogInputLine = Color3.fromRGB(176, 138, 146),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(150, 100, 110),
	HoverChange = 0.06
}
