return {
	Accent = Color3.fromRGB(140, 60, 220),

	AcrylicMain = Color3.fromRGB(14, 10, 22),
	AcrylicBorder = Color3.fromRGB(107, 79, 155),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(58, 27, 91), Color3.fromRGB(9, 6, 14)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(69, 49, 105),
	Tab = Color3.fromRGB(118, 92, 162),

	Element = Color3.fromRGB(100, 70, 150),
	ElementBorder = Color3.fromRGB(11, 8, 18),
	InElementBorder = Color3.fromRGB(107, 79, 155),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(100, 70, 150),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(100, 70, 150),

	DropdownFrame = Color3.fromRGB(131, 107, 171),
	DropdownHolder = Color3.fromRGB(13, 9, 20),
	DropdownBorder = Color3.fromRGB(11, 8, 17),
	DropdownOption = Color3.fromRGB(100, 70, 150),

	Keybind = Color3.fromRGB(100, 70, 150),

	Input = Color3.fromRGB(123, 97, 165),
	InputFocused = Color3.fromRGB(9, 6, 14),
	InputIndicator = Color3.fromRGB(138, 116, 176),

	Dialog = Color3.fromRGB(13, 9, 20),
	DialogHolder = Color3.fromRGB(11, 8, 18),
	DialogHolderLine = Color3.fromRGB(10, 7, 16),
	DialogButton = Color3.fromRGB(13, 9, 20),
	DialogButtonBorder = Color3.fromRGB(112, 84, 158),
	DialogBorder = Color3.fromRGB(100, 70, 150),
	DialogInput = Color3.fromRGB(32, 28, 38),
	DialogInputLine = Color3.fromRGB(138, 116, 176),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(100, 70, 150),
	HoverChange = 0.06
}
