return {
	Accent = Color3.fromRGB(100, 150, 100),

	AcrylicMain = Color3.fromRGB(244, 247, 242),
	AcrylicBorder = Color3.fromRGB(199, 209, 194),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(222, 232, 220), Color3.fromRGB(245, 247, 243)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(207, 209, 205),
	Tab = Color3.fromRGB(199, 209, 194),

	Element = Color3.fromRGB(210, 220, 205),
	ElementBorder = Color3.fromRGB(183, 185, 181),
	InElementBorder = Color3.fromRGB(189, 198, 184),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(210, 220, 205),
	ToggleToggled = Color3.fromRGB(100, 150, 100),

	SliderRail = Color3.fromRGB(210, 220, 205),

	DropdownFrame = Color3.fromRGB(178, 187, 174),
	DropdownHolder = Color3.fromRGB(244, 247, 242),
	DropdownBorder = Color3.fromRGB(195, 197, 193),
	DropdownOption = Color3.fromRGB(210, 220, 205),

	Keybind = Color3.fromRGB(210, 220, 205),

	Input = Color3.fromRGB(189, 198, 184),
	InputFocused = Color3.fromRGB(245, 248, 243),
	InputIndicator = Color3.fromRGB(147, 154, 143),

	Dialog = Color3.fromRGB(244, 247, 242),
	DialogHolder = Color3.fromRGB(231, 234, 229),
	DialogHolderLine = Color3.fromRGB(214, 217, 212),
	DialogButton = Color3.fromRGB(244, 247, 242),
	DialogButtonBorder = Color3.fromRGB(193, 202, 188),
	DialogBorder = Color3.fromRGB(210, 220, 205),
	DialogInput = Color3.fromRGB(231, 234, 229),
	DialogInputLine = Color3.fromRGB(157, 165, 153),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(210, 220, 205),
	HoverChange = 0.06
}
