return {
	Accent = Color3.fromRGB(240, 150, 190),

	AcrylicMain = Color3.fromRGB(20, 14, 18),
	AcrylicBorder = Color3.fromRGB(164, 117, 136),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(97, 61, 78), Color3.fromRGB(13, 9, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(111, 76, 90),
	Tab = Color3.fromRGB(171, 127, 145),

	Element = Color3.fromRGB(160, 110, 130),
	ElementBorder = Color3.fromRGB(17, 11, 15),
	InElementBorder = Color3.fromRGB(164, 117, 136),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(160, 110, 130),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(160, 110, 130),

	DropdownFrame = Color3.fromRGB(179, 139, 155),
	DropdownHolder = Color3.fromRGB(19, 13, 17),
	DropdownBorder = Color3.fromRGB(16, 11, 14),
	DropdownOption = Color3.fromRGB(160, 110, 130),

	Keybind = Color3.fromRGB(160, 110, 130),

	Input = Color3.fromRGB(174, 131, 148),
	InputFocused = Color3.fromRGB(13, 9, 11),
	InputIndicator = Color3.fromRGB(183, 146, 161),

	Dialog = Color3.fromRGB(19, 13, 17),
	DialogHolder = Color3.fromRGB(17, 11, 15),
	DialogHolderLine = Color3.fromRGB(15, 10, 13),
	DialogButton = Color3.fromRGB(19, 13, 17),
	DialogButtonBorder = Color3.fromRGB(167, 121, 140),
	DialogBorder = Color3.fromRGB(160, 110, 130),
	DialogInput = Color3.fromRGB(37, 32, 36),
	DialogInputLine = Color3.fromRGB(183, 146, 161),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(160, 110, 130),
	HoverChange = 0.06
}
