return {
	Accent = Color3.fromRGB(60, 160, 230),

	AcrylicMain = Color3.fromRGB(240, 247, 252),
	AcrylicBorder = Color3.fromRGB(190, 209, 223),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(213, 233, 248), Color3.fromRGB(241, 247, 252)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(204, 209, 214),
	Tab = Color3.fromRGB(190, 209, 223),

	Element = Color3.fromRGB(200, 220, 235),
	ElementBorder = Color3.fromRGB(180, 185, 189),
	InElementBorder = Color3.fromRGB(180, 198, 211),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(200, 220, 235),
	ToggleToggled = Color3.fromRGB(60, 160, 230),

	SliderRail = Color3.fromRGB(200, 220, 235),

	DropdownFrame = Color3.fromRGB(170, 187, 199),
	DropdownHolder = Color3.fromRGB(240, 247, 252),
	DropdownBorder = Color3.fromRGB(192, 197, 201),
	DropdownOption = Color3.fromRGB(200, 220, 235),

	Keybind = Color3.fromRGB(200, 220, 235),

	Input = Color3.fromRGB(180, 198, 211),
	InputFocused = Color3.fromRGB(242, 248, 252),
	InputIndicator = Color3.fromRGB(140, 154, 164),

	Dialog = Color3.fromRGB(240, 247, 252),
	DialogHolder = Color3.fromRGB(228, 234, 239),
	DialogHolderLine = Color3.fromRGB(211, 217, 221),
	DialogButton = Color3.fromRGB(240, 247, 252),
	DialogButtonBorder = Color3.fromRGB(184, 202, 216),
	DialogBorder = Color3.fromRGB(200, 220, 235),
	DialogInput = Color3.fromRGB(228, 234, 239),
	DialogInputLine = Color3.fromRGB(150, 165, 176),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(200, 220, 235),
	HoverChange = 0.06
}
