return {
	Accent = Color3.fromRGB(140, 120, 220),

	AcrylicMain = Color3.fromRGB(15, 14, 20),
	AcrylicBorder = Color3.fromRGB(107, 103, 145),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(58, 51, 90), Color3.fromRGB(9, 9, 13)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(70, 66, 98),
	Tab = Color3.fromRGB(118, 114, 153),

	Element = Color3.fromRGB(100, 95, 140),
	ElementBorder = Color3.fromRGB(12, 11, 17),
	InElementBorder = Color3.fromRGB(107, 103, 145),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(100, 95, 140),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(100, 95, 140),

	DropdownFrame = Color3.fromRGB(131, 127, 163),
	DropdownHolder = Color3.fromRGB(14, 13, 19),
	DropdownBorder = Color3.fromRGB(12, 11, 16),
	DropdownOption = Color3.fromRGB(100, 95, 140),

	Keybind = Color3.fromRGB(100, 95, 140),

	Input = Color3.fromRGB(123, 119, 157),
	InputFocused = Color3.fromRGB(9, 9, 13),
	InputIndicator = Color3.fromRGB(138, 135, 168),

	Dialog = Color3.fromRGB(14, 13, 19),
	DialogHolder = Color3.fromRGB(12, 11, 17),
	DialogHolderLine = Color3.fromRGB(11, 10, 15),
	DialogButton = Color3.fromRGB(14, 13, 19),
	DialogButtonBorder = Color3.fromRGB(112, 107, 149),
	DialogBorder = Color3.fromRGB(100, 95, 140),
	DialogInput = Color3.fromRGB(33, 32, 37),
	DialogInputLine = Color3.fromRGB(138, 135, 168),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(100, 95, 140),
	HoverChange = 0.06
}
