return {
	Accent = Color3.fromRGB(60, 120, 220),

	AcrylicMain = Color3.fromRGB(245, 246, 248),
	AcrylicBorder = Color3.fromRGB(199, 202, 209),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(217, 227, 243), Color3.fromRGB(246, 246, 248)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(208, 209, 210),
	Tab = Color3.fromRGB(199, 202, 209),

	Element = Color3.fromRGB(210, 213, 220),
	ElementBorder = Color3.fromRGB(183, 184, 186),
	InElementBorder = Color3.fromRGB(189, 191, 198),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(210, 213, 220),
	ToggleToggled = Color3.fromRGB(60, 120, 220),

	SliderRail = Color3.fromRGB(210, 213, 220),

	DropdownFrame = Color3.fromRGB(178, 181, 187),
	DropdownHolder = Color3.fromRGB(245, 246, 248),
	DropdownBorder = Color3.fromRGB(196, 196, 198),
	DropdownOption = Color3.fromRGB(210, 213, 220),

	Keybind = Color3.fromRGB(210, 213, 220),

	Input = Color3.fromRGB(189, 191, 198),
	InputFocused = Color3.fromRGB(246, 247, 249),
	InputIndicator = Color3.fromRGB(147, 149, 154),

	Dialog = Color3.fromRGB(245, 246, 248),
	DialogHolder = Color3.fromRGB(232, 233, 235),
	DialogHolderLine = Color3.fromRGB(215, 216, 218),
	DialogButton = Color3.fromRGB(245, 246, 248),
	DialogButtonBorder = Color3.fromRGB(193, 195, 202),
	DialogBorder = Color3.fromRGB(210, 213, 220),
	DialogInput = Color3.fromRGB(232, 233, 235),
	DialogInputLine = Color3.fromRGB(157, 159, 165),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(210, 213, 220),
	HoverChange = 0.06
}
