return {
	Accent = Color3.fromRGB(100, 150, 200),

	AcrylicMain = Color3.fromRGB(15, 17, 20),
	AcrylicBorder = Color3.fromRGB(103, 122, 145),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(44, 63, 83), Color3.fromRGB(9, 11, 13)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(67, 80, 98),
	Tab = Color3.fromRGB(114, 131, 153),

	Element = Color3.fromRGB(95, 115, 140),
	ElementBorder = Color3.fromRGB(12, 14, 17),
	InElementBorder = Color3.fromRGB(103, 122, 145),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(95, 115, 140),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(95, 115, 140),

	DropdownFrame = Color3.fromRGB(127, 143, 163),
	DropdownHolder = Color3.fromRGB(14, 16, 19),
	DropdownBorder = Color3.fromRGB(12, 13, 16),
	DropdownOption = Color3.fromRGB(95, 115, 140),

	Keybind = Color3.fromRGB(95, 115, 140),

	Input = Color3.fromRGB(119, 136, 157),
	InputFocused = Color3.fromRGB(9, 11, 13),
	InputIndicator = Color3.fromRGB(135, 150, 168),

	Dialog = Color3.fromRGB(14, 16, 19),
	DialogHolder = Color3.fromRGB(12, 14, 17),
	DialogHolderLine = Color3.fromRGB(11, 12, 15),
	DialogButton = Color3.fromRGB(14, 16, 19),
	DialogButtonBorder = Color3.fromRGB(107, 126, 149),
	DialogBorder = Color3.fromRGB(95, 115, 140),
	DialogInput = Color3.fromRGB(33, 35, 37),
	DialogInputLine = Color3.fromRGB(135, 150, 168),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(95, 115, 140),
	HoverChange = 0.06
}
