return {
	Accent = Color3.fromRGB(130, 150, 180),

	AcrylicMain = Color3.fromRGB(13, 15, 18),
	AcrylicBorder = Color3.fromRGB(98, 107, 122),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(53, 62, 74), Color3.fromRGB(8, 9, 11)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(63, 70, 81),
	Tab = Color3.fromRGB(109, 118, 131),

	Element = Color3.fromRGB(90, 100, 115),
	ElementBorder = Color3.fromRGB(11, 12, 15),
	InElementBorder = Color3.fromRGB(98, 107, 122),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(90, 100, 115),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(90, 100, 115),

	DropdownFrame = Color3.fromRGB(123, 131, 143),
	DropdownHolder = Color3.fromRGB(12, 14, 17),
	DropdownBorder = Color3.fromRGB(10, 12, 14),
	DropdownOption = Color3.fromRGB(90, 100, 115),

	Keybind = Color3.fromRGB(90, 100, 115),

	Input = Color3.fromRGB(114, 123, 136),
	InputFocused = Color3.fromRGB(8, 9, 11),
	InputIndicator = Color3.fromRGB(131, 138, 150),

	Dialog = Color3.fromRGB(12, 14, 17),
	DialogHolder = Color3.fromRGB(11, 12, 15),
	DialogHolderLine = Color3.fromRGB(9, 11, 13),
	DialogButton = Color3.fromRGB(12, 14, 17),
	DialogButtonBorder = Color3.fromRGB(103, 112, 126),
	DialogBorder = Color3.fromRGB(90, 100, 115),
	DialogInput = Color3.fromRGB(31, 33, 36),
	DialogInputLine = Color3.fromRGB(131, 138, 150),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(90, 100, 115),
	HoverChange = 0.06
}
