return {
	Accent = Color3.fromRGB(240, 130, 60),

	AcrylicMain = Color3.fromRGB(22, 16, 14),
	AcrylicBorder = Color3.fromRGB(164, 117, 88),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(98, 55, 30), Color3.fromRGB(14, 10, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(111, 77, 56),
	Tab = Color3.fromRGB(171, 127, 101),

	Element = Color3.fromRGB(160, 110, 80),
	ElementBorder = Color3.fromRGB(18, 13, 11),
	InElementBorder = Color3.fromRGB(164, 117, 88),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(160, 110, 80),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(160, 110, 80),

	DropdownFrame = Color3.fromRGB(179, 139, 115),
	DropdownHolder = Color3.fromRGB(20, 15, 13),
	DropdownBorder = Color3.fromRGB(17, 12, 11),
	DropdownOption = Color3.fromRGB(160, 110, 80),

	Keybind = Color3.fromRGB(160, 110, 80),

	Input = Color3.fromRGB(174, 131, 106),
	InputFocused = Color3.fromRGB(14, 10, 9),
	InputIndicator = Color3.fromRGB(183, 146, 123),

	Dialog = Color3.fromRGB(20, 15, 13),
	DialogHolder = Color3.fromRGB(18, 13, 11),
	DialogHolderLine = Color3.fromRGB(16, 12, 10),
	DialogButton = Color3.fromRGB(20, 15, 13),
	DialogButtonBorder = Color3.fromRGB(167, 121, 94),
	DialogBorder = Color3.fromRGB(160, 110, 80),
	DialogInput = Color3.fromRGB(38, 34, 32),
	DialogInputLine = Color3.fromRGB(183, 146, 123),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(160, 110, 80),
	HoverChange = 0.06
}
