return {
	Accent = Color3.fromRGB(50, 180, 210),

	AcrylicMain = Color3.fromRGB(10, 17, 20),
	AcrylicBorder = Color3.fromRGB(84, 136, 150),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(24, 74, 86), Color3.fromRGB(6, 11, 13)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(52, 90, 101),
	Tab = Color3.fromRGB(96, 145, 158),

	Element = Color3.fromRGB(75, 130, 145),
	ElementBorder = Color3.fromRGB(8, 14, 17),
	InElementBorder = Color3.fromRGB(84, 136, 150),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(75, 130, 145),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(75, 130, 145),

	DropdownFrame = Color3.fromRGB(111, 155, 167),
	DropdownHolder = Color3.fromRGB(9, 16, 19),
	DropdownBorder = Color3.fromRGB(8, 13, 16),
	DropdownOption = Color3.fromRGB(75, 130, 145),

	Keybind = Color3.fromRGB(75, 130, 145),

	Input = Color3.fromRGB(102, 148, 161),
	InputFocused = Color3.fromRGB(6, 11, 13),
	InputIndicator = Color3.fromRGB(120, 161, 172),

	Dialog = Color3.fromRGB(9, 16, 19),
	DialogHolder = Color3.fromRGB(8, 14, 17),
	DialogHolderLine = Color3.fromRGB(7, 12, 15),
	DialogButton = Color3.fromRGB(9, 16, 19),
	DialogButtonBorder = Color3.fromRGB(89, 140, 153),
	DialogBorder = Color3.fromRGB(75, 130, 145),
	DialogInput = Color3.fromRGB(28, 35, 37),
	DialogInputLine = Color3.fromRGB(120, 161, 172),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(75, 130, 145),
	HoverChange = 0.06
}
