return {
	Accent = Color3.fromRGB(160, 230, 60),

	AcrylicMain = Color3.fromRGB(14, 18, 10),
	AcrylicBorder = Color3.fromRGB(126, 155, 88),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(65, 92, 27), Color3.fromRGB(9, 11, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(82, 103, 55),
	Tab = Color3.fromRGB(136, 162, 101),

	Element = Color3.fromRGB(120, 150, 80),
	ElementBorder = Color3.fromRGB(11, 15, 8),
	InElementBorder = Color3.fromRGB(126, 155, 88),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(120, 150, 80),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(120, 150, 80),

	DropdownFrame = Color3.fromRGB(147, 171, 115),
	DropdownHolder = Color3.fromRGB(13, 17, 9),
	DropdownBorder = Color3.fromRGB(11, 14, 8),
	DropdownOption = Color3.fromRGB(120, 150, 80),

	Keybind = Color3.fromRGB(120, 150, 80),

	Input = Color3.fromRGB(140, 165, 106),
	InputFocused = Color3.fromRGB(9, 11, 6),
	InputIndicator = Color3.fromRGB(153, 176, 123),

	Dialog = Color3.fromRGB(13, 17, 9),
	DialogHolder = Color3.fromRGB(11, 15, 8),
	DialogHolderLine = Color3.fromRGB(10, 13, 7),
	DialogButton = Color3.fromRGB(13, 17, 9),
	DialogButtonBorder = Color3.fromRGB(130, 158, 94),
	DialogBorder = Color3.fromRGB(120, 150, 80),
	DialogInput = Color3.fromRGB(32, 36, 28),
	DialogInputLine = Color3.fromRGB(153, 176, 123),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(120, 150, 80),
	HoverChange = 0.06
}
