return {
	Accent = Color3.fromRGB(180, 20, 50),

	AcrylicMain = Color3.fromRGB(14, 8, 10),
	AcrylicBorder = Color3.fromRGB(117, 65, 74),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(72, 12, 24), Color3.fromRGB(9, 5, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(76, 38, 45),
	Tab = Color3.fromRGB(127, 79, 87),

	Element = Color3.fromRGB(110, 55, 65),
	ElementBorder = Color3.fromRGB(11, 6, 8),
	InElementBorder = Color3.fromRGB(117, 65, 74),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(110, 55, 65),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(110, 55, 65),

	DropdownFrame = Color3.fromRGB(139, 95, 103),
	DropdownHolder = Color3.fromRGB(13, 7, 9),
	DropdownBorder = Color3.fromRGB(11, 6, 8),
	DropdownOption = Color3.fromRGB(110, 55, 65),

	Keybind = Color3.fromRGB(110, 55, 65),

	Input = Color3.fromRGB(131, 85, 93),
	InputFocused = Color3.fromRGB(9, 5, 6),
	InputIndicator = Color3.fromRGB(146, 105, 112),

	Dialog = Color3.fromRGB(13, 7, 9),
	DialogHolder = Color3.fromRGB(11, 6, 8),
	DialogHolderLine = Color3.fromRGB(10, 6, 7),
	DialogButton = Color3.fromRGB(13, 7, 9),
	DialogButtonBorder = Color3.fromRGB(121, 71, 80),
	DialogBorder = Color3.fromRGB(110, 55, 65),
	DialogInput = Color3.fromRGB(32, 26, 28),
	DialogInputLine = Color3.fromRGB(146, 105, 112),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(110, 55, 65),
	HoverChange = 0.06
}
