return {
	Accent = Color3.fromRGB(220, 150, 60),

	AcrylicMain = Color3.fromRGB(250, 246, 235),
	AcrylicBorder = Color3.fromRGB(213, 204, 185),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(245, 231, 208), Color3.fromRGB(250, 246, 237)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(212, 209, 199),
	Tab = Color3.fromRGB(213, 204, 185),

	Element = Color3.fromRGB(225, 215, 195),
	ElementBorder = Color3.fromRGB(187, 184, 176),
	InElementBorder = Color3.fromRGB(202, 193, 175),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(225, 215, 195),
	ToggleToggled = Color3.fromRGB(220, 150, 60),

	SliderRail = Color3.fromRGB(225, 215, 195),

	DropdownFrame = Color3.fromRGB(191, 182, 165),
	DropdownHolder = Color3.fromRGB(250, 246, 235),
	DropdownBorder = Color3.fromRGB(200, 196, 188),
	DropdownOption = Color3.fromRGB(225, 215, 195),

	Keybind = Color3.fromRGB(225, 215, 195),

	Input = Color3.fromRGB(202, 193, 175),
	InputFocused = Color3.fromRGB(250, 247, 238),
	InputIndicator = Color3.fromRGB(157, 150, 136),

	Dialog = Color3.fromRGB(250, 246, 235),
	DialogHolder = Color3.fromRGB(237, 233, 223),
	DialogHolderLine = Color3.fromRGB(220, 216, 206),
	DialogButton = Color3.fromRGB(250, 246, 235),
	DialogButtonBorder = Color3.fromRGB(207, 197, 179),
	DialogBorder = Color3.fromRGB(225, 215, 195),
	DialogInput = Color3.fromRGB(237, 233, 223),
	DialogInputLine = Color3.fromRGB(168, 161, 146),

	Text = Color3.fromRGB(30, 30, 30),
	SubText = Color3.fromRGB(90, 90, 90),
	Hover = Color3.fromRGB(225, 215, 195),
	HoverChange = 0.06
}
