return {
	Accent = Color3.fromRGB(70, 180, 160),

	AcrylicMain = Color3.fromRGB(10, 16, 15),
	AcrylicBorder = Color3.fromRGB(88, 136, 126),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(31, 73, 65), Color3.fromRGB(6, 10, 9)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(55, 90, 83),
	Tab = Color3.fromRGB(101, 145, 136),

	Element = Color3.fromRGB(80, 130, 120),
	ElementBorder = Color3.fromRGB(8, 13, 12),
	InElementBorder = Color3.fromRGB(88, 136, 126),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(80, 130, 120),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(80, 130, 120),

	DropdownFrame = Color3.fromRGB(115, 155, 147),
	DropdownHolder = Color3.fromRGB(9, 15, 14),
	DropdownBorder = Color3.fromRGB(8, 12, 12),
	DropdownOption = Color3.fromRGB(80, 130, 120),

	Keybind = Color3.fromRGB(80, 130, 120),

	Input = Color3.fromRGB(106, 148, 140),
	InputFocused = Color3.fromRGB(6, 10, 9),
	InputIndicator = Color3.fromRGB(123, 161, 153),

	Dialog = Color3.fromRGB(9, 15, 14),
	DialogHolder = Color3.fromRGB(8, 13, 12),
	DialogHolderLine = Color3.fromRGB(7, 12, 11),
	DialogButton = Color3.fromRGB(9, 15, 14),
	DialogButtonBorder = Color3.fromRGB(94, 140, 130),
	DialogBorder = Color3.fromRGB(80, 130, 120),
	DialogInput = Color3.fromRGB(28, 34, 33),
	DialogInputLine = Color3.fromRGB(123, 161, 153),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(80, 130, 120),
	HoverChange = 0.06
}
