return {
	Accent = Color3.fromRGB(120, 80, 220),

	AcrylicMain = Color3.fromRGB(6, 6, 10),
	AcrylicBorder = Color3.fromRGB(79, 69, 117),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(45, 31, 83), Color3.fromRGB(3, 3, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(47, 41, 75),
	Tab = Color3.fromRGB(92, 83, 127),

	Element = Color3.fromRGB(70, 60, 110),
	ElementBorder = Color3.fromRGB(5, 5, 8),
	InElementBorder = Color3.fromRGB(79, 69, 117),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(70, 60, 110),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(70, 60, 110),

	DropdownFrame = Color3.fromRGB(107, 99, 139),
	DropdownHolder = Color3.fromRGB(5, 5, 9),
	DropdownBorder = Color3.fromRGB(4, 4, 8),
	DropdownOption = Color3.fromRGB(70, 60, 110),

	Keybind = Color3.fromRGB(70, 60, 110),

	Input = Color3.fromRGB(97, 89, 131),
	InputFocused = Color3.fromRGB(3, 3, 6),
	InputIndicator = Color3.fromRGB(116, 108, 146),

	Dialog = Color3.fromRGB(5, 5, 9),
	DialogHolder = Color3.fromRGB(5, 5, 8),
	DialogHolderLine = Color3.fromRGB(4, 4, 7),
	DialogButton = Color3.fromRGB(5, 5, 9),
	DialogButtonBorder = Color3.fromRGB(84, 75, 121),
	DialogBorder = Color3.fromRGB(70, 60, 110),
	DialogInput = Color3.fromRGB(25, 25, 28),
	DialogInputLine = Color3.fromRGB(116, 108, 146),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(70, 60, 110),
	HoverChange = 0.06
}
