return {
	Accent = Color3.fromRGB(210, 255, 60),

	AcrylicMain = Color3.fromRGB(14, 16, 10),
	AcrylicBorder = Color3.fromRGB(136, 155, 79),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(82, 99, 27), Color3.fromRGB(9, 10, 6)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(89, 103, 49),
	Tab = Color3.fromRGB(145, 162, 92),

	Element = Color3.fromRGB(130, 150, 70),
	ElementBorder = Color3.fromRGB(11, 13, 8),
	InElementBorder = Color3.fromRGB(136, 155, 79),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(130, 150, 70),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(130, 150, 70),

	DropdownFrame = Color3.fromRGB(155, 171, 107),
	DropdownHolder = Color3.fromRGB(13, 15, 9),
	DropdownBorder = Color3.fromRGB(11, 12, 8),
	DropdownOption = Color3.fromRGB(130, 150, 70),

	Keybind = Color3.fromRGB(130, 150, 70),

	Input = Color3.fromRGB(148, 165, 97),
	InputFocused = Color3.fromRGB(9, 10, 6),
	InputIndicator = Color3.fromRGB(161, 176, 116),

	Dialog = Color3.fromRGB(13, 15, 9),
	DialogHolder = Color3.fromRGB(11, 13, 8),
	DialogHolderLine = Color3.fromRGB(10, 12, 7),
	DialogButton = Color3.fromRGB(13, 15, 9),
	DialogButtonBorder = Color3.fromRGB(140, 158, 84),
	DialogBorder = Color3.fromRGB(130, 150, 70),
	DialogInput = Color3.fromRGB(32, 34, 28),
	DialogInputLine = Color3.fromRGB(161, 176, 116),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(130, 150, 70),
	HoverChange = 0.06
}
