return {
	Accent = Color3.fromRGB(160, 40, 60),

	AcrylicMain = Color3.fromRGB(16, 10, 12),
	AcrylicBorder = Color3.fromRGB(117, 69, 79),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(66, 20, 28), Color3.fromRGB(10, 6, 7)),
	AcrylicNoise = 0.9,

	TitleBarLine = Color3.fromRGB(77, 42, 49),
	Tab = Color3.fromRGB(127, 83, 92),

	Element = Color3.fromRGB(110, 60, 70),
	ElementBorder = Color3.fromRGB(13, 8, 10),
	InElementBorder = Color3.fromRGB(117, 69, 79),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(110, 60, 70),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(110, 60, 70),

	DropdownFrame = Color3.fromRGB(139, 99, 107),
	DropdownHolder = Color3.fromRGB(15, 9, 11),
	DropdownBorder = Color3.fromRGB(12, 8, 9),
	DropdownOption = Color3.fromRGB(110, 60, 70),

	Keybind = Color3.fromRGB(110, 60, 70),

	Input = Color3.fromRGB(131, 89, 97),
	InputFocused = Color3.fromRGB(10, 6, 7),
	InputIndicator = Color3.fromRGB(146, 108, 116),

	Dialog = Color3.fromRGB(15, 9, 11),
	DialogHolder = Color3.fromRGB(13, 8, 10),
	DialogHolderLine = Color3.fromRGB(12, 7, 9),
	DialogButton = Color3.fromRGB(15, 9, 11),
	DialogButtonBorder = Color3.fromRGB(121, 75, 84),
	DialogBorder = Color3.fromRGB(110, 60, 70),
	DialogInput = Color3.fromRGB(34, 28, 30),
	DialogInputLine = Color3.fromRGB(146, 108, 116),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(110, 60, 70),
	HoverChange = 0.06
}
